### ISSUE TITLE
Edit/manage AIP FileSets

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#119]
## Story
As a Preservation Curator, I want to view and edit File Sets assigned to the overall object package, so that I can manage the preservation package's files over time

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Relates #127 and #22 (creating and categorizing File Sets); to #96 (labeling individual preservation files). This epic focuses on how to edit File Sets that have already been created and assigned to a Work. The interface for editing a File Set can largely be re-used from the Create interface, but we will also need to add the ability to re-order File Sets in a work as well as to delete File Sets from a work.  

Some work has been re-scoped to an enhancement epic #349 to do post-migration.

#### Links to Additional Information
[Possible View/Manage Flows for Works and FileSets](https://docs.google.com/drawings/d/1eV8C6eG1Yugk49dGB9oEQSE9x0rKKbRF4fffK-NP5Z4/edit)
[Mockup: View/Manage a FileSet view from a work page: basic functions](https://docs.google.com/drawings/d/1zCogYOtCNI1UtYlVMmHnYI_e3M0Uv4OLC4FzFShu1wg/edit)
[View all attached files from View FileSet page](https://docs.google.com/drawings/d/1CXdEhXmj73Yt1xsd2h_aeQE-7EtLcVghztkTHv19Z8s/edit)
[Mockup for editing FileSets already attached to a work](https://docs.google.com/drawings/d/11wjr5PuMNjIArFCaXNoTbdPY1_r__XuEFv_Ezd3eWHQ/edit) 
[Hyrax - basic file management](https://samvera.github.io/edit-works-2.0.html#editing-a-work---file-manager)
[Hyrax - Edit File and File Manager Forms: Screenshots](https://docs.google.com/document/d/1acUwZMgG5RgWc6M2FA60Pyxb0dENXU4v4TLiv_Ja-0U/edit?usp=sharing)

#### Checklist
- [x] View all attached FileSets from a Work Page
- [x] Interface to manage a FileSet's Title/Name
- [x] Interface to see and download all the files attached to a FileSet
- [x] View the FileSet Use category assigned to an existing set (Primary, Supplemental, etc.)
- [x] Interface to manage additional properties for a FileSet (Visibility)
- [x] Add additional Files to an existing Set [use Edit Work form]

De-scoped to separate enhancement ticket:
* Delete a FileSet from an existing work (but validate that at least one FileSet exists)
* Interface to manage overall display order for FileSets within a work
* Interface to edit the FileSet Use category assigned to an existing Set (Primary, Suppl. etc.)
* Change/replace a file for a given File Use within an existing Set
* Delete a File from an existing Set
* Test "Versions" tab in Hyrax when editing a File Set
* Provide navigation to edit/manage individual Files through the standard Hyrax File Manager, such as changing visibility or permissions for a specific file
* Assign/change the default Thumbnail for the set (consider Hyrax UI vs. custom Emory thumbnail selection)

**Comment by eporter23** [comment]
Tested: the basic Hyrax Edit Fileset form allows us to change the Title for a FileSet, as well as change Visibility for the entire FileSet.
