### ISSUE TITLE
Assign DLP visibility options for Curate and Lux works/files

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#120]
## Story
As a Collection Manager or Repository Administrator, I want to enable tiered visibility options for objects and their component files, so that I can provide access to end users while respecting rights and agreements related to the work

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
For v.1/MVP, we need to have the ability to make objects/files: 
* Public
* Emory network
* Private: Restricted to Curate users only based on their group permissions (A Curate depositor set something as "Dark" end then assign view or edit Sharing permissions so that a specific Curate user group can view/edit the material when logged in)

Additional access controls will be needed in future releases. We will also need to provide IIIF/Universal viewer configurations for files for some v.1 material (related to Migration release)

#### Links to Additional Information
[Mockup for Visibility Options](https://docs.google.com/drawings/d/14jjPpK0zz6MCOGW05uAki-y0TlYNiiSS4Z0w_ipNUaI/edit)
[Approved DLP Visibility Requirements](https://wiki.service.emory.edu/display/DLPP/Permissions+Matrix+and+Analysis#PermissionsMatrixandAnalysis-AppendixB:VisibilityLevels)

#### Checklist
- [x] Public
- [x] Emory network users only
- [x] Private (Restrict to specific Curate product user groups only)
- [x] Standard Hyrax Embargo option (no embargoed content for v.1 content)
- [x] Standard Hyrax Lease option (not anticipated for v.1 content)
- [x] Visibility options apply to both Works and Files
- [x] Additional options can be configured for IIIF manifests and the Universal Viewer in a future release 

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
@rotated8 @alexBLR @devanshu-m I just tested the "Private" setting in Nurax. It looks like assigning the standard Hyrax visibility level of "Private" and then adding Sharing permissions to a specific Curate user or Curate group will achieve what I originally wanted for "restrict to Curate users".

**Comment by eporter23** [comment]
6/13: tested all except Lease, Embargo. File-level visibility works in combination with Object level (meaning you can have a Public object + require login for a specific file).

**Comment by eporter23** [comment]
Tested a basic file-level embargo; works with expected/known Hyrax behavior.
