### ISSUE TITLE
Auto-complete metadata for selected uncontrolled text fields

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#124]
## Story
As a Metadata Specialist or Staff Depositor, I want to implement auto-complete/type-ahead for selected fields, so that depositors using a form can enter data more quickly and consistently when using a form 

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Some uncontrolled text fields such as keywords would benefit from having an auto-complete feature to help similar entries become more consistent.

Priority:
Some fields which _should_ use an authority, but entries may not always exist, like Creators (could be Emory people or formally defined authority entries):
- [x]   Institution (D1)
- [x]   Subject – Time Periods (D33)
- [x]   Role – Creator (D45)
- [x]   Role – Contributor (D46)
- [x]   Role Sponsor (D50)
- [x]   Role - Grant/Funding Agency (D53)
- [x]   Rights Holder (D58)

Enhancement: other fields will not draw from a formal authority, but may benefit from auto-complete if they have already been populated in the repository by other Emory depositors:
* Keywords (D29)
* Conference/Meeting Name (D34)
* Parent Work Title (D38)

#### Links to Additional Information
[Metadata implementation worksheet](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=673932450)
[Auto-suggest field recommendations](https://wiki.service.emory.edu/pages/viewpage.action?pageId=119147632#Metadata/DataEntryFunctionalRequirements-ValuesEnteredasStringsvs.URIs)
[CV Usage Notes](https://docs.google.com/document/d/1kVkpjVMK5-tmQGuH0hJuXTafI5Ba3B3RarkGCiOeEtY/edit#)

#### Checklist
- [ ] Priority - enable users to enter custom terms for selected QA fields (see above)

#### Given/When/Then
* Given I am a Curate user editing metadata using the generic work form 
* When I am entering a person, organization or event name that doesn't exist in a major authority 
* Then I can enter my own term in the field (and ideally other Curate users can use it too)

**Comment by eporter23** [comment]
At 4/30 release planning we discussed this being a nice to have but not urgent feature. Revisit this if time permits in the schedule.

**Comment by eporter23** [comment]
5/10: Pending revisions from testing (noted in dependent issues)
