### ISSUE TITLE
Validate selected metadata fields as URIs in an editing form

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#125]
## Story
As a Metadata Specialist, I want selected metadata fields to be entered as URIs, so that they can either be presented to end users as actionable links or be interpreted by a lookup service to provide additional information from a linked source

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
See also #76 for fields that can be strings or URIs and #65 for fields using controlled terms. 

The checklist items below should be validated as fully qualified http/https actionable URLs to provide links to non-repository sources.  

#### Checklist
- [x] Final Published Version
- [x] Related Material - Publications
- [x] Related Material - Datasets
- [x] Rights Documentation URI
