### ISSUE TITLE
Create compound/multi-part objects through deposit form

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#127]
## Story
As a Preservation Curator, I want to use a deposit form to upload multiple types of files for a given work and provide context for them within the digital object, so that I can support long-term access to the material in alignment with Emory's AIP specification

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Provides a create interface to #22 and #23
See also acceptance criteria for file use assignment.

#### Links to Additional Information
[Upload multiple files to a FileSet and assign them to different AIP sections](https://docs.google.com/drawings/d/1IdxhFHEKZ8pNyOl6As7bMRgWHLTA2Q6jhj8Ma8Sl4PE/edit?usp=sharing) 
[Assign component file use through deposit form] (https://docs.google.com/drawings/d/1S87A5y1dOjA6d4-9FYOOw8OChLG1U-rTG8sdIm3hn1M/edit)

#### Checklist
- [x] Ability to create File Sets within different AIP sections during deposit/create work process
- [x] Ability to upload individual files into File Sets during upload process
- [x] Ability to assign a file use to files within a File Set during deposit/create work process
 ~~Validation that at least one FileSet must created for either Primary Content or Supplemental Content~~
- [x] Validation that at a Preservation Master file should be assigned for any given File Set, and other File Uses are optional
- [x] Validation that a use can only be assigned once within a given File Set (e.g. only one master per Set)
- [x] Ability to optionally provide a manual Display Label to a File Set during deposit/create work process
- [x] Ability to delete an accidental/empty File Set before finalizing deposit [confirm with testing: FileSet uploader will permit blank filesets as long as one is populated with a pres. master]

Deferred:
* Ability to re-order File Sets before finalizing deposit [de-scoped for Create Work process - will treat as enhancement]
[Re-order FileSets before ingest](https://docs.google.com/drawings/d/1pqjgKQYWmg8scF-lO__bKF9mqd08PT8y3JzVcsfNKrM/edit?usp=sharing)
[Delete FileSet before ingest](https://docs.google.com/drawings/d/1aIxIxsSqw1dHWRHApJ_Of4hT81wTWiBKBeSEf-Ydumk/edit?usp=sharing)

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Can simplify this by making the category of file set a drop-down option (removing the three headings/section approach in mockups)

**Comment by eporter23** [comment]
This epic isn't selectable for issues for some reason.

**Comment by eporter23** [comment]
Discussed at 7/30 release planning: the current Create Work behavior for creating filesets will allow a user to save a new work with an empty fileset attached, as long as there is at least one fileset with a preservation master file assigned. Additional "delete" fileset actions are addressed in epic #119 (Edit/Manage FileSets)
