### ISSUE TITLE
Prototype Deposit Collections for large collection performance issues

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1301]
_As a Repository Administrator, I want to ensure that large collection ingests complete within a reliable, reasonable timeframe, so that additional material can be ingested to keep up with demand for preservation_

**Notes**

With the Langmuir collection specifically, once we ingested ~6,000 works, the rate of ingest began to slow exponentially. The current rate of ingest is one work every two hours; when we first began ingesting Langmuir it was approximately 50 works per hour. We have also tested depositing Langmuir material into a brand new empty collection and the rate of ingest is approximately 50-60 works per hour.

**To prototype:**

Each work will have a primary source collection for each work (uses the existing Library Collection type). For small collections, the source collection (Library Collection type) and the deposit collection are one and the same. For very large collections, we may also create additional "overflow" deposit collections (a new Collection Type: Deposit Collection) as the ingest performance declines. A work would have a membership to its deposit collection and also its source collection, but the source collection is a separate relationship that is locally defined. We also need to ensure that for a source collection, it has a relationship defined to any additional deposit collections.

Main idea:
When a work is deposited into a Collection in Hyrax currently, this relationship is defined by member_of_collection fields:
member_of_collection_ids_ssim
member_of_collections_ssim

Moving forward, every work would now receive 2 Collection relationships:

1. the collection ID it was deposited into (same as above)
2. the source collection ID that is related to the collection the work was deposited into

For large collections:

- The Source Collection is created first, with the type Library Collection and serves as both a Source and Deposit Collection.
- As the collection grows and if performance degrades, additional Deposit Collections are created with distinct ids.
- As Deposit Collections are created, they are related to the Source (Library Collection type) Collection.
- All materials in a given "real world" collection have the same Source Collection, but may be associated with a single, distinct Deposit Collection.

For smaller collections:

- The  Source Collection ID will be the same as the Deposit Collection id.

See this [slide deck for additional notes](https://docs.google.com/presentation/d/19npT7wUU1N2FCCJdazpMPcXb8m4dOukN9CnY8Abv9TQ/edit#slide=id.p)

Wireframes:
- Curate - [Collection Dashboard: All Collections](https://docs.google.com/drawings/d/15tNfAJUa62jTQGbBorPPKVboa1GFAhT1VMWMj7lfFD0/edit)
- Curate - [View Collection details: Source Collection](https://docs.google.com/drawings/d/18ofPgmsO6H3LQdxgTInCw-jyMtOcZ7b9qaNwbKM7z_c/edit)
- Curate -[ View Collection details: Deposit Collection](https://docs.google.com/drawings/d/18zAPiFxsVH12Oq5mXhNb_Bz6i025fjhvdHXriAANJvA/edit)
- Curate - [Create/Edit Collection](https://docs.google.com/drawings/d/1w8W1lAFsUV7kKWkJdnzCR1xsJjyYtel4_XP6SPMRlmU/edit)
- Curate - [Work Dashboard](https://docs.google.com/drawings/d/16I0cKv7kwZ7OeDWW6KW_xlnx2-3MYBJ3D1vrAccD0gU/edit)
- Curate - [View Work](https://docs.google.com/drawings/d/1QlhvkVxhXByBJYoWr587wx10YLbv0HYXP7W9bhx6AC0/edit)
- Curate - [Create/Edit Work - v1](https://docs.google.com/drawings/d/1aHmM2AY1y4AosdVQcmOgeaL5GxYhoqebYbkKrAmB22g/edit)
- Curate - [Create/Edit Work - v2](https://docs.google.com/drawings/d/16KWbOhooGWYj0-C92Jp1oq_0ptjHELTCtZwysfAlpNg/edit)
- Curate - [Import from CSV](https://docs.google.com/drawings/d/1RlFWkHNDKaVaB1YQf0Isi7sH7DvUaJIUJENC3dyteaE/edit)
- Lux - [Collection Facet and Explore Our Collections](https://docs.google.com/drawings/d/1YgdgM42JQFSYC_0DbljJllgfczUTMIiM5biolUxI4p8/edit)
- Lux - [View Work](https://docs.google.com/drawings/d/1wISDQmRHzYIr-PFBlK0K0wad5wdpycUYvJAraRxN01k/edit)

Possible Curate changes:
- [ ] New Collection Type: Deposit Collection (see example in Curate Test)
- [ ] Updates to View Collection pages
- [ ] Updates to Collection dashboard view
- [ ] New metadata fields to relate Source and Deposit collections
- [ ] Updates to Works counts shown in various views
- [ ] Updates to CSV importer to add any additional fields needed for the new relationship
- [ ] Updates to Collection forms to assign the additional relationship if applicable
- [ ] Changes to indexing processes?
- [ ] Changes to collection file count rake task?

Possible Lux changes
- [ ] Update Lux facet to include only Source Collection affiliation
- [ ] Update Lux Explore Collections query to include only source collections (exclude Deposit Collections)
- [ ] Update Lux breadcrumbs to include only Source Collection links
- [ ] Update Lux Show Work page to display only the source collection affiliation
- [ ] Update Lux search results snipped to display only the source collection affiliation

Additional changes needed (after ramp down development completed):

- [ ] Collection counts in Explore Collections (Lux)
- [ ] Collection counts in search result previews for collections (Curate, Lux)
- [x] View Items in this Digital Collection link query (Lux)

**Comment by rotated8** [comment]
We'd recommend breaking this ticket into multiple pieces:
- All the development around adding this to works
- All the development around adding this to collections
- The data update/initialization
- All the Lux updates

**Comment by eporter23** [comment]
8/4/20 breakout session notes - discussed that adding the Source Collection IDs to Fedora will be needed, but can omit the Title for better performance. Next steps: start with adding the relationships manually at the work level, and then move to the importer and collection-level relationships as needed.

**Comment by eporter23** [comment]
8/6/20 breakout session: broke out multiple tickets for initial works and collections changes, but epic still needs further tickets created.
