### ISSUE TITLE
Documentation for Operations and Service Transition

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1398]
## Story
As a Repository Administrator, I want to document our systems architecture and major Samvera application customizations, so that as the Cor infrastructure moves into production, we are better able to respond to incidents and support requests

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic is a catch-all for different types of documentation and operational transition activities that involve the Scrum team.

#### Links to Additional Information
Add [links](https://www.emory.edu/) here

#### Checklist
- [x] Update/expand documentation for AWS infrastructure
- [x] Document current storage utilization
- [x] Document Curate/Hyrax software customizations

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
