### ISSUE TITLE
Configure misc. metadata form fields for data entry

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#148]
## Story
As a Metadata Specialist, I want to provide guidance/data entry controls for selected Curate metadata form fields, so that data is entered in a consistent way

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic may be updated to add misc. form mockups as needed.

#### Links to Additional Information
[Example form mockup - additional field validation notes](https://docs.google.com/document/d/1JdpnbNyk-SlNhORX5MU0kRdEcrZbpU6NesWEf5y5bEY/edit#heading=h.bswnvn1q1xl4)
[Metadata Implementation Worksheet](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=673932450)

#### Checklist
- [x] Ensure that repeating vs. non-repeating fields are validated from Metadata Implementation worksheet
- [x] Ensure that required vs non-required fields are validated from Metadata Implementation Worksheet
- [x] Require a valid date or allow a machine-readable unknown date entry in Date Created field
- [x] Institution: set form's default value to "Emory University"

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Moved system of record prefixes over to #203 (Form Enhancements).

**Comment by eporter23** [comment]
Some aspects of Date Created validation are still in revision, but closing this because it can be tested separately.
