### ISSUE TITLE
Support custom access control and file delivery scenarios in Universal Viewer

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#154]
## Story
As a Collection Manager or Library Staff Depositor, I want to assign either standard or restricted Lux content viewer settings as part of my deposit process, so that I can easily enable appropriate Lux viewer restrictions if my material has special restrictions on viewing or downloading

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
For some collections migrated into Curate, we will need to configure more restrictive viewing and downloading options for the IIIF manifest/Universal Viewer (as used in both Curate and Lux). Ideally we could toggle a finite set of visibility options, plus a finite set of UV configuration options. This content viewer toolbar configuration might be stored as new administrative metadata. Additionally, the objects stored in Curate may have multiple derivatives assigned, and some file versions are more appropriate for the UV than others.

#### Links to Additional Information
[Universal Viewer Configuration options - GitHub; no formal documentation?](https://github.com/UniversalViewer/universalviewer/blob/master/src/extensions/uv-seadragon-extension/config/en-GB.json#L113)
[Visibility + File Quality + Universal Viewer Configuration Settings](https://docs.google.com/spreadsheets/d/1f9wNcOXkpasu3ED_flfJuMxy1mWG4U_FWli__HXO-_k/edit#gid=0)
[Derivative selection options for UV Display for complex objects](https://docs.google.com/document/d/1lIcmfMqusaZUmePnHmfCZK0UecjkFPVPtBUxJHWe2fw/edit?usp=sharing) - TBD: should this be a separate epic?

#### Checklist
- [x] A depositor can select the appropriate combination of controls through the Curate user interface or by supplying metadata as part of bulk ingest
- [x] Content delivered in the Curate and Lux application can be managed by a combination of Visibility/discoverability by distinct groups, variable levels of file quality, and variable ability to download or only view content 
- [x] Content delivered to the Lux application may include showing an Intermediate or Service File instead of the Preservation Master File
- [x] A depositor can select the appropriate file derivative to display using metadata or the product interface; OR, patterns are enforced automatically based on which File Use options have been populated for a FileSet
- [x] Restricting "Download" includes disabling download, print, and sharing options in the Universal Viewer toolbar
- [x] The access control parameters for authentication and file quality sent to the Lux viewer are also part of the IIIF manifest for other IIIF viewers to respect
- [x] The set of access control combinations noted above can be expanded over time

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
