### ISSUE TITLE
Expand Featured Collections on Lux homepage

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1607]
_As a repository administrator, I want an interface to manage the Featured Collections section of the Lux homepage, so that multiple libraries can showcase their content and users do not see outdated content_

Acceptance Criteria

- [ ] Repository administrators can allow more than 3 collections to be featured, using an interface option either in Curate or Lux to flag which collections should be featured
- [ ] A randomized set of 3 featured collections will display (in the current layout) when the page loads
- [ ] The randomly loaded 3 featured collections do not cycle on a timer like the carousel does, but remain visible until the page is refreshed
- [ ] The existing banner image for the collection as assigned in Curate can be re-used and scaled down for display for the Featured Collection image content

Mockup showing randomized set of 3 featured collections:
![Screen Shot 2023-01-18 at 8.47.46 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/a9f4dd9a-cbb8-431b-b78f-7802bff3e972)

Mockup showing re-use of existing collection banner scaled to fit the container (min-height:100%; width: 150%)

![Featured Image Collex Scale2.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/6a775f13-09a1-4626-b61d-ab20e8683fb2)

Prototype for Lux Randomized Display:

- http://emilyporter.net/emory/lux21/lux-random.html
- This includes a set of 6 collection divs; 3 of which are randomly selected and shown.

**Comment by eporter23** [comment]
@bwatson78 for development purposes, here are 3 full URLs to the banner images currently on the homepage to use in the new admin UI: 
Health Sciences Artifacts
https://curate.library.emory.edu//branding/5053ffbg7n-cor/banner/HS-S023_B067_P004.jpg

Langmuir
https://curate.library.emory.edu//branding/914nk98sfv-cor/banner/40644j0ztx-cor.jpg

Oxford Asian Artifacts
https://curate.library.emory.edu//branding/320sqv9s4v-cor/banner/OXKOBE_045_P0001.jpg

Here are a few more if you want more than 3 to work with:
https://curate.library.emory.edu//branding/7784j0zqdg-cor/banner/hero-sizer-eecp2.jpg

https://curate.library.emory.edu//branding/607gqnk9qx-cor/banner/8719b_sized.jpg

**Comment by bwatson78** [comment]
@eporter23 Of course!
