### ISSUE TITLE
Upgrade Curate to Hyrax 3.1

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1644]
## Story
_As a Repository Administrator, I want to upgrade Curate to the last version of Hyrax, so that product users benefit from enhancements and we do not lose pace with changes in the Samvera codebase_

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Add notes here

#### Links to Additional Information
[Previous regression test plan](https://docs.google.com/spreadsheets/d/1GkbYyr1u_COLVp4BUDIlkX4dXM6kWudxiI8w1sIZJq8/edit#gid=1785783084)
[Previous epic to upgrade to beta 3](https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/979)

#### Checklist

- [x] Update regression test plan ([template](https://docs.google.com/spreadsheets/d/1BTjC_8_mHr49ktUJiOFLYixCNOa3Rdv5nuhdDiOx6_w/edit#gid=2120660950)) for Curate/Lux to include Source Collection features; UI for bulk tasks
- [x] Identify number of versions needed to upgrade and test 
- [x] Identify work tickets for code analysis related to versions and changes
- [x] Conduct technical testing and re-development where needed
- [x] Conduct regression testing (test and prod environments)
- [ ] Fix bugs identified during regression testing
- [ ] Schedule any required downtime for users

**Comment by bwatson78** [comment]
Progression of versions:

1. Current Version:     3.0.0-rc1
2. v3.0.0.pre.rc1:        identical
3. v3.0.0-rc2:             674 commits, 1624 Files changed
4. v3.0.0.pre.rc2:       identical
5. v3.0.0.pre.rc3:       332 commits, 649 Files changed
6. v3.0.0.pre.rc4:       106 commits, 130 Files changed
7. v3.0.0:                    65 commits, 120 Files changed

**Comment by devanshu-m** [comment]
**Actors:** We have an overwrite for file_set_actor. There is an update in the latest version so we will need to update our repo copy as well.
**Note:** https://github.com/samvera/hyrax/compare/v3.0.0.pre.rc1...v3.1.0#diff-a694e81bc27f122f74d44924272e5ddf9a32aeeb429313bac091831fac8630ffR103
Add of a file_set to work's ordered members is done in the attach_files_to_work_job in curate. Refer: https://github.com/emory-libraries/dlp-curate/blob/main/app/jobs/attach_files_to_work_job.rb#L67
We might need to look at this change in more detail.

**Comment by bwatson78** [comment]
Assets:
- app/assets/javascripts/hyrax/app.js.erb
- app/assets/javascripts/hyrax/collections/editor.es6

Plus respective Rspec

**Comment by devanshu-m** [comment]
**Controllers:** 
**CollectionTypesController:** Params for collection_types_controller are updated in v3.1.0 hyrax. We have overwritten the params method and will require to look at this file when updating and also its respective spec.
**DownloadsController:** We have overwritten this file and there have been updates to it in the new hyrax version. We will need to update this file and its spec.
**FileSetsController: ** We have overwritten this file and there have been updates to it in the new hyrax version. We will need to update this file and its spec.
**FixityChecksController:** We have overwritten this file and there have been updates to it in the new hyrax version. We will need to update this file and its spec.
**UploadsController:** We have overwritten this file and there have been updates to it in the new hyrax version. We will need to update this file and its spec.

^ some of the files above have additions for wings and valkyrie work but they have consequential modifications for AF as well. It will be best to update all of these and then look at what changes we want to do from our previous overwrites. Also, some of the file changes could just well be adding `# frozen_string_literal: true` which we might have done already in our overwrites.

**Comment by bwatson78** [comment]
Forms:
- app/forms/hyrax/forms/admin/collection_type_form.rb
- app/forms/hyrax/forms/collection_form.rb

**Comment by bwatson78** [comment]
Indexers:
- app/indexers/curate_collection_indexer.rb
- CurateIndexer < ActiveFedora::RDF::IndexingService (This is a maybe--we'll have to check the AF gem when we address this category.)

**Comment by bwatson78** [comment]
Jobs:
- app/jobs/attach_files_to_work_job.rb
- app/jobs/characterize_job.rb
- app/jobs/fixity_check_job.rb

**Comment by devanshu-m** [comment]
**Helpers:**
**AbilityOverrideHelper:** We have overridden the ability_helper and there have been updates to it in the new hyrax version. We will need to update this file and its spec.
**CollectionsOverrideHelper:** We have overridden the collections_helper and there have been updates to it in the new hyrax version. We will need to update this file and its spec.
**IIIFHelper**: We have overwritten this file and there have been updates to it in the new hyrax version. We will need to update this file and its spec.

**Comment by devanshu-m** [comment]
**Presenters:**
**FileSetPresenter:** We have overwritten delegations in this file and there have been updates to it in the new hyrax version. We will need to update this file and its spec.
**AdminSetPresenter:** We have overwritten this file and there have been updates to it in the new hyrax version. We will need to update this file and its spec.
**CharacterizationBehavior:** We have overwritten this file and there have been updates to it in the new hyrax version. We will need to update this file and its spec.
**CollectionPresenter:** We have overwritten this file and there have been updates to it in the new hyrax version. We will need to update this file and its spec.

**Comment by devanshu-m** [comment]
**SearchBuilders:**
**CollectionMemberSearchBuilder:** We have overwritten this file and there have been updates to it in the new hyrax version. We will need to update this file and its spec.

**Comment by devanshu-m** [comment]
**Services:**
**FileSetFixityCheckService:** We have overwritten this file and there have been updates to it in the new hyrax version. We will need to update this file and its spec.
**ManifestBuilderService:** This file looks like a new introduction in Hyrax-3.1.0. We might want to stick to our implementation of the manifest builder service.

**Comment by devanshu-m** [comment]
**Initializers:**
**FileActor:** We have overwritten part this file (opened up instance method - ingest_file) and there have been updates to it in the new hyrax version. We will need to update this file and its spec.
**JobIoWrapper:** We have overwritten this file and there have been updates to it in the new hyrax version. We will need to update this file and its spec.
**HyraxMyWorksController**: We have overwritten this file (configure_facets method) and there have been updates to it in the new hyrax version. We will need to update this file and its spec.
****

**Comment by bwatson78** [comment]
Models: 
- app/models/concerns/hyrax/collection_behavior.rb
- app/models/concerns/hyrax/file_set/characterization.rb
- app/models/curate/collection_type.rb
- app/models/hyrax/uploaded_file.rb

**Comment by bwatson78** [comment]
Views:
- app/views/_controls.html.erb
- app/views/catalog/_index_list_default.html.erb
- app/views/hyrax/base/_form.html.erb
- app/views/hyrax/base/_form_visibility_component.html.erb
- app/views/hyrax/base/_show_actions.html.erb
- app/views/hyrax/collections/_show_descriptions.html.erb
- app/views/hyrax/collections/show.html.erb
- app/views/hyrax/dashboard/collections/_form.html.erb
- app/views/hyrax/dashboard/collections/_form_branding.html.erb
- app/views/hyrax/dashboard/collections/_show_descriptions.html.erb
- app/views/hyrax/dashboard/collections/new.html.erb
- app/views/hyrax/dashboard/collections/show.html.erb
- app/views/hyrax/dashboard/sidebar/_tasks.html.erb
- app/views/hyrax/file_sets/_show_actions.html.erb
- app/views/hyrax/file_sets/show.html.erb
- app/views/hyrax/my/_collection_action_menu.html.erb
- app/views/hyrax/users/_vitals.html.erb
- app/views/records/edit_fields/_title.html.erb
- app/views/shared/_citations.html.erb

**Comment by bwatson78** [comment]
Miscellaneous (and questionable if we need to update):
- db/seeds.rb
- .circleci/config.yml
- Gemfile
- Rakefile
