### ISSUE TITLE
Generate persistent identifiers for the Cor repository

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#17]
## Story
As a Library Staff Depositor, I want to have a unique, persistent identifier created and assigned for  ingested objects or collections, so that repository resources have a stable, unique identifier that resolves to a URL for long term access and citation purposes 

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
PID scheme (NOID-based; prefixed; with a specified amount of digits; these values will not collide with legacy Emory PIDs or Laevigata PIDs). We will mint and store IDs for files, objects and collections, but support persistence for objects and collections. See also epic #206 for storing in metadata.

REVISION, SEPT: 2019:
the _cor-_ prefix convention has been flagged as problematic for Fedora 4 performance related to its pair tree structures. We are revising this to become a suffix instead.

For Emory's ID convention, we will generate a 10 digit alphanumeric sequence: _123???????_ followed by a text suffix "-cor." 

* _123_ are random, numeric values 
* _???????_ are random alphabetic or numeric values
* _-cor_ is a text suffix to indicate a Cor-generated ID

ORIGINAL:
For Emory's ID convention, we will add a text prefix "cor." using a period as a delimiter plus a 10 digit alphanumeric sequence: _cor.123???????_ 

* _cor._ is a text prefix to indicate a Cor-generated ID (note the period at the end)
* _123_ are random, numeric values 
* _???????_ are random alphabetic or numeric values
#### Links to Additional Information
Dated but useful [background information on NOIDs in Samvera[(https://github.com/mlibrary/hydra-prototype/wiki/How-it-Works:-Noids)
[Estimation worksheet for scale of PIDs needed over time](https://docs.google.com/spreadsheets/d/1Ty-a9NM88CcXi7AOsXo8knLcEQYGLONRylgAKGBqJd8/edit#gid=64116209)

#### Checklist
- [x] NOID based scheme as indicated above
(https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=1362694572&range=8:8)
- [x] IDs are generated such that they will be unique across Curate, Self Deposit
- [x] Items in the repository can be actionable/accessed using the asset's ID for the Curate, Self Deposit and Lux applications
- [x] IDs generated by the repository should not be editable or deleted by end users
- [x] The Cor repository ID scheme should only be used for the repository; IDs should only be minted as part of an ingest process
- [x] NOIDs are generated for Works
- [x] NOIDS are generated for Files
- [x] NOIDS are generated for Collections

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Based on constraints with Samvera's NOID-minter, we adapted the original pattern from cor.abc1234???? to cor.123????????

**Comment by eporter23** [comment]
@alexBLR looks like you closed this Epic, but I haven't been able to test it yet, so I am moving back into In Progress.

**Comment by bess** [comment]
This was noted on a previous ticket, but this identifier scheme is going to cause performance issues. All of your objects will be in a top level directory called /co/ ... that's going to slow down fedora operations.

**Comment by eporter23** [comment]
Thanks @bess - @rotated8 and I are discussing this.
