### ISSUE TITLE
Upgrade Curate to Hyrax 3.0.2

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1750]
## Story
As a repository administrator, I want to upgrade Curate to a more current version of Hyrax, so that we can take advantage of enhancements and not lose pace with community development

#### Checklist
- [x] Perform upgrade in arch
- [x] Conduct[ basic regression testing](https://docs.google.com/spreadsheets/d/1xSbxmS6BdL8dsRCqiUhYQGCD8-FNgDqYAInp4mILyJs/edit#gid=668832311) in arch
- [x] Upgrade in test
- [x] Perform in-depth regression testing in test
- [ ] Upgrade in production
- [ ] Perform basic regression testing in production
