### ISSUE TITLE
Restrict public discovery of selected metadata fields in Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#18]
## Story
As a Collection Manager/Library Staff Depositor/Metadata Specialist, I want to restrict the ability to view selected Administrative, Rights, and Preservation metadata, so that end users or non-Library staff do not see staff notes that are irrelevant or contain sensitive information

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
The DLP Metadata Application Profile contains a number of metadata properties that are intended to be visible/editable by selected user groups only using the Curate interface. These are flagged as "Staff Only" in the "Displays To" column of all metadata spreadsheets. The majority of metadata fields in the Rights, Administrative, Preservation, and Technical metadata sections should be visible to staff only.

We need to restrict selected metadata from displaying to users who may discover the Curate application if the interface is publicly available at curate.library.emory.edu.

#### Links to Additional Information
Add [links](https://www.emory.edu/) here - ADD LINK to consolidated metadata spreadsheet

#### Checklist
- [ ] All properties are visible within the Curate application to [SPECIFY ANY GROUP EXCEPTIONS]
- [ ] All properties except those in the Technical segment are editable within the Curate application (they are generated by FITS and should not be manually modified)
- [ ] Only metadata properties marked as "End Users and Staff" in the DLP metadata profile display in the show page for a work in Curate

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Discussed briefly in 3/26 release planning - we will be able to specify the "show page" metadata for works in Curate in addition to what we will do for Lux. This will enable us to only display selected Descriptive and Rights information.

**Comment by eporter23** [comment]
Currently, Curate shows all populated metadata fields. If a user has authorization to see a work, they will see all/any fields populated. if this becomes a concern, we can look at more granular field-level display options.
