### ISSUE TITLE
Prototype full-text searching

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#2003]
## Story
As a Collection Manager, I want users to be able to search the contents of textual works, so that their searches reveal more detailed matches beyond metadata

As a Repository User, I want to see matches on keywords within a textual object in search results, so that I have a sense of what the text contains related to my search entry

As a Repository user, I want to search within an individual text object I am viewing, so that I don't have to download the material and search on my local machine

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This ticket follows an earlier spike ticket to assess what is needed, indexing-wise, to support full-text searching across works in the repository as well as within an individual work using the Universal Viewer. For this ticket, we will aim for creating a functional prototype that we can use to get additional feedback from users. 

#### Links to Additional Information
[Rose library enhancement request](https://github.com/emory-libraries/dlp-enhance/issues/18)
[Investigation ticket for indexing needs](https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/1813)

#### Checklist
- [ ] A user can perform a basic keyword search which will search against available full text indexed fields in SOLR
- [ ] A user can see a preview of full text matches in search results
- [ ] A user will see matching results at the individual work-level (not a complex parent-child result)
- [ ] A user can see an option in the Universal Viewer to search within a specific work (if available/indexed)
- [ ] A user can see visual highlighting within pages when searching in the Universal Viewer
- [ ] A repository administrator can reindex selected works to make them full-text searchable

**Comment by eporter23** [comment]
@abelemlih closing this epic because we are now continuing on with a new epic.
