### ISSUE TITLE
Investigate exporting with Bulkrax

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#2017]
_As a Repository Administrator, I want to export metadata and files from the repository, so that I can assist with patron requests for full-object downloads_

_As a Metadata Specialist, I want to export metadata for ingested works, so that I can make bulk edits to a spreadsheet for re-importing back into the repository_

For this epic, we want to test Bulkrax's export capabilities for the following

- Exporting metadata only as a CSV for selected works or collections
- Exporting works' metadata and files as a BagIt or ZIP file

*Acceptance criteria*

- [x] 1 For metadata exports, the resulting CSV file should match our importer heading columns to assist with re-imports
- [x] 2 Only Repository Administrators can see the Exporters interface
- [x] For file exports, the file must be able to be re-associated with its parent work either by its filename or other metadata
- [x] 3 The exporter UI should include a Title column like we have added for the Importers interface to assist with troubleshooting
- [x] 4 Any populated Preservation Workflow metadata for works should be included in the exported CSV output as they are formatted in CSVs for input, e.g. with columns as follows. Note that these are the most commonly populated, but this pattern extends to Decommission and Deletion entries. See tickets #791 and #1557 for prior work related to bulk import of preservation workflow data.
-- Ingest.workflow_notes	
-- Ingest.workflow_rights_basis	
-- Ingest.workflow_rights_basis_date	
-- Ingest.rights_basis_reviewer	
-- Ingest.workflow_rights_basis_note
-- Ingest.workflow_rights_basis_uri
-- Accession.workflow_rights_basis	
-- Accession.workflow_rights_basis_date	
-- Accession.workflow_rights_basis_reviewer	
-- Accession.workflow_rights_basis_note
-- Accession.workflow_rights_basis_uri
- [x] 5 A user should be able to specify a set of works/collections/filesets to export by their IDs in addition to the default Bulkrax selection options, which are not useful to many of our local needs. See [wireframe for possible implementation idea](https://docs.google.com/drawings/d/1Uk4nIU6XRIjB_-k84ZFwYxv2RPVv9RURWz49x2JBb-E/edit). The export should contain the children of the IDs specified (e.g. if a work is specified, its fileset entries should also be exported). 
- [x] 6 When fileset entries are exported, the creator column should be left blank. Currently Bulkrax assigns the depositor's user id as the creator, but this is confusing if the metadata and/or files are being shared with a patron requested the information.

**Comment by eporter23** [comment]
Initial testing with basic Bulkrax exports:

For metadata exports, the resulting CSV renames multi-valued fields with _1 at the end of the header, even if there is only a single value stored. When there are multiple values, it also splits into multiple columns (e.g. data_collection_dates_1 and data_collection_dates_2).

**Comment by eporter23** [comment]
The selection options for exporting are not very useful in their current state. You can select by an existing importer, an entire collection, or X number of works in a Collection or Work Type. If you use the X number selection, it selects from oldest works deposited first. Ideally we could have a way to manually specify works by ID or by a lookup option.

**Comment by eporter23** [comment]
When exporting files and metadata, there is no fileset metadata exported. The files are exported with their original filenames, and it is difficult to relate them back to their parent work (which references the Curate ID and not the filename).

**Comment by eporter23** [comment]
Good news is that we are able to export works that were not imported using Bulkrax!

**Comment by eporter23** [comment]
Exporting using an existing Importer fails without even starting in sidekiq. I am not sure if we are currently deleting those importer directories off the Curate server, but perhaps that is the culprit.

**Comment by eporter23** [comment]
@bwatson78 I wrote some brief acceptance criteria above. As a next step can you please look at the first item in that checklist which is to adjust the exported CSV output so it matches our import CSV format? Depending on how that goes we can talk about the other items later.

**Comment by bwatson78** [comment]
PR #2068 addresses the third task on the list.

**Comment by eporter23** [comment]
Items 4 and 6 look great @bwatson78.

**Comment by eporter23** [comment]
item 5 is working really well! One note from latest testing is that we are still having occurrences of certain columns outputting multiples in new columns appended with  _1. See https://curate-test.library.emory.edu/exporters/24?locale=en
1:27
The FileSet row is outputting some work-level metadata for a handful of fields, all of which are doing the _1 quirk. Odd that it's happening on abstract which isn't multi-valued? Columns I noticed are: `abstract_1`, `publisher_1`. `date_created` is also repeating the value from the work on the fileset, which isn't a problem, just a little odd.

**Comment by eporter23** [comment]
@bwatson78 prod exports are looking great!
