### ISSUE TITLE
Metadata Form Enhancements

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#203]
## Story
As a Library Staff Depositor, I want to enhance the readability of the data entry form, so that the purpose of specific form fields and how to populate them is clear 

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic outlines usability enhancements for the metadata form, following initial development in 0.3 release. Some of these enhancements will be needed to support migration testing. 

* Human-friendly field labels
* Multi-line/longer text fields for notes, abstracts

#### Links to Additional Information
[Metadata Implementation - Objects Worksheet](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589)

#### Checklist
- [x] Remove or hide any Hyrax-default field guidance/definition text
- [x] [Specified fields can accommodate multi-line/long text entries] (https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589&fvid=1207540610)
- [x] [Re-label work form fields using values from Display Label column] (https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589&range=V:V)
- [x] Require a four-digit date for years (include leading zeros)?

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Testing notes:
#268, #270 done except: 
Rights Statement and Rights Statement Controlled need to be swapped and Rights Statement needs to be a textarea field - relates to #310
#269 needs minor revisions for Page Range; Rights Statement labels
