### ISSUE TITLE
Preservation Storage with 2+ copies

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#205]
## Story
As a Repository Administrator or Preservation Curator, I want to ensure that 2 or more copies of repository assets are stored in preservation quality storage environments, so that the Libraries minimize risk of data loss and to align with industry best practices

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
For version 1, we will support at least 2 copies through S3 with cross-regional replication. Long term, we will increase our support through 3 copies, with geographic and technological diversity (not all copies stored in AWS). Relates to epic for Replication Event and #254 Ingest Workflow.

#### Links to Additional Information
[Digital Preservation FRG Storage Recommendations](https://wiki.service.emory.edu/display/DLPP/Preservation+Storage+Recommendations)
[AWS S3 with cross-region replication](https://docs.aws.amazon.com/AmazonS3/latest/dev/crr.html)

#### Checklist
- [x] 2 copy durable storage in S3 (through regional replication or other means)
- [x] Minimum of 5TB will be needed for production for Phase 1 migrations
- [x] Additional storage needed for test for Phase 1 migrations

Optional/related work:
* When files are stored in S3, we may record a confirmation as a Replication Event in the Preservation Log

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
