### ISSUE TITLE
Preservation Event: Technical Metadata Extraction for Files

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#208]
## Story
As a Preservation Curator, I want to extract and store additional metadata supplied by Hyrax and FITS for files, so that selected characterization metadata can be indexed for search and display for end users or staff and is retained as part of preservation metadata

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Additional technical metadata should be stored and indexed for preservation master files to support staff search and reporting needs. Hyrax (and HydraWorks) provide extraction and indexing for selected fields; DLP requirements match these and identify some additional properties. 

DISCUSS: do we store and index at the file-level or file-set level? Given that most of our objects have multiple files, this would get confusing at the object level.

The [DLP Technical Metadata requirements](https://wiki.service.emory.edu/display/DLPP/Technical+Metadata) gathered in 2018 may be out of date relative to ongoing FITS releases but serve as an overview and background for technical metadata needed for preservation.

#### Links to Additional Information
[DLP File & FileSet/Technical Metadata](https://docs.google.com/spreadsheets/d/1csDcDnJdhB1VLlgJUU95DndXSeIP2j8yPMlErrsVVPw/edit#gid=1836172006)
[Samvera Technical Metadata Profile](https://wiki.duraspace.org/display/samvera/Technical+Metadata+Application+Profile): baseline technical metadata to which we will add more
[HydraWorks extraction/characterization](https://github.com/samvera/hydra-works/tree/master/lib/hydra/works/characterization/schema): baseline technical metadata to which we will add more
[Approved Preservation Events & Workflows](https://wiki.service.emory.edu/display/DLPP/Preservation+Event+and+Workflow+Recommendations)
[Preservation - Metadata Properties Needed](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=497852377)
[Preservation Log - XML Mockup](https://drive.google.com/file/d/1osxuTL2rCbu_aasE5xTXIK9pazrSwIN3/view?usp=sharing)
[List of all Preservation UI Mockups](https://docs.google.com/document/d/1z8sa020Kj4NJvreVGxxEWnXV_NGdAjUJQdMz3sRbDk8/edit#heading=h.lheatu9c6eeg)

#### Checklist
- [x] Technical metadata will be extracted for files during the deposit process, and selected properties will be stored as indexed RDF for search/display/reporting purposes
- [x] Metadata will be stored at the file-level or FileSet-level
- [x] If technical characterization data is stored at the File-Set level only, it should store technical details for the Preservation Master File
- [x] If characterization data is captured for all files in a FileSet, that metadata should be stored at the File-level
- [x] Technical Metadata extraction should run as part of either Accession or Ingest workflow, depending on the best sequence for Hyrax and Fedora
- [ ] In future versions, users should be able to run or request characterization on demand
- [x] In v.1, technical metadata properties have been identified for Images and Text; additional properties will be needed for audiovisual material

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by rotated8** [comment]
Are we characterizing all the files or only the preservation master? Currently, Hyrax stores the technical MD at the FileSet level.

**Comment by eporter23** [comment]
Closing this epic, but this Preservation Event does need to be captured in the Event log (separate epics and tickets)
