### ISSUE TITLE
Retain the full FITS output as supplemental preservation file

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#209]
## Story
As a Preservation Curator, I want to retain the full FITS output as supplemental preservation file, so that all of the available characterization data is retained for preservation, beyond what Hyrax software captures

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Default Hyrax functionality is to use FITS to generate technical metadata, extract a selection of fields as indexed RDF, but then Hyrax discards the resulting output file (typically an XML file). We want to keep the full output file for staff users to read/download if needed because FITS provides a great deal of useful technical detail.

Alternative: would it be possible to keep the FITS file for preservation masters only, and store that on the FileSet as a new use?

#### Links to Additional Information
Add [links](https://www.emory.edu/) here

#### Checklist
- [ ] FITS outputs (e.g. XML file) for Preservation Master files assigned to Primary Content FileSets generated during Curate ingest should be kept as a binary file. FITS outputs should NOT be retained for Supplemental Content or Supplemental Preservation FileSets.
- [ ] If a filenaming scheme is needed, use the filename from the Preservation Master file + append "-FITS", so that users can determine which file the FITS is describing    
- [ ] Retained FITS output binary files should be assigned as a Preservation Master file use to a Supplemental Preservation FileSet
- [ ] For very complex objects with many similar Primary Content master files (e.g. a book with many pages which are TIFFs), only retain the _first_ instance of a given mime type (e.g. the first TIFF)
- [ ] Assign the original filename of the categorized file as a suffix to any automatically generated FITS output filenames, to differentiate them (e.g. _FITS-originalfilename.xml_) 

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Discussed with Rosalyn: this may cause too much complexity related to workflow event sequences. Recommend we make characterization on demand as an enhancement, and allow users to download the FITS (but not automatically storing it). If we do not store FITS, we need to make sure we extract and store as much FITS as possible as File metadata.

**Comment by eporter23** [comment]
I am closing this because we are retaining most of the FITS-extracted technical metadata and have not found it necessary to store the FITS file.
