### ISSUE TITLE
Store a copy of DAMS metadata with bulk-ingest for images

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#21]
## Story
As a Collection Manager or Preservation Curator, I want to store a static copy of a legacy metadata record along with the digital object, so that I can store additional read-only metadata that is not part of the repository's metadata profile

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
For material ingested to the repository from the DAMS workflow, additional metadata exists that does not all map to the DLP metadata profile. We want to keep a copy of the metadata as a supplemental binary file that is part of the preservation package. Relates to separate epic for storing a copy of extracted Alma record files (#218) and separate epic for bulk ingest method (#273).

Metadata is generated by the DAMS for each file, and it contains manually entered metadata as well as technical metadata that it generates. 

Outcome: decided this could be achieved much more simply by creating an administrative object per collection and attaching the full collection metadata dump CSV to that, instead of trying to split it to one record per each object. (See #542)

#### Links to Additional Information
Generic SIP Mapping for images
Data Sources for Phase 1 Migrations
Related epic #219 - extract DAMS metadata
Related epic #218 - store a copy of Alma MARC XML file
Related epic #273 - bulk ingest process

#### Checklist
- [ ] Preferred option 1: One copy of a DAMS record per object is stored
- [ ] Alternate option 2: one copy of a DAMS record is stored for each file
- [x] Alternate option 3: a private administrative object is created for the collection, which contains the DAMS metadata for the whole collection along with other DCSC documentation
- [ ] All DAMS metadata records stored with a work will be assigned to a Supplemental Preservation FileSet, with the file serving as the Preservation Master file
- [ ] DAMS metadata records stored as Preservation Master files will receive standard file-related preservation events (to be confirmed, ongoing work in 0.4)

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
