### ISSUE TITLE
Event - Fixity Checking

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#217]
## Story
As a Preservation Curator, I want to run a Fixity Check service on my objects, so that I can monitor for changes to all the files associated with an object or more broadly across the whole repository

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Our assumption is for v.1, we can run fixity checks only on SHA1, because that is consistently assigned to all files. We should provide options for 
1) a self-service fixity check available to all Curate users 
2) a scheduled run of multiple files in batches  
3) the ability to generate a summary report about ongoing fixity checks in the repository (based on #2)

#### Links to Additional Information
[Approved Preservation Events & Workflows](https://wiki.service.emory.edu/display/DLPP/Preservation+Event+and+Workflow+Recommendations)
[Preservation - Metadata Properties Needed](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=497852377)
[Sample Event Output for Fixity Check](https://docs.google.com/document/d/1O_Ut_j8ZAf9WdMGOUNwreM-WVEZ04rKictnUWg3-BLA/edit#heading=h.653h645i8pbx)
Related epic: Preservation Reporting

#### Checklist
- [x] If using Fedora 4's fixity service, runs fixity checks on all Preservation Master Files using their SHA1 checksum (see enhancement notes)
- [x] Fixity checks can be run on demand for a given FileSet using the Curate/Hyrax UI
- [ ] Fixity checks will run on a schedule (at least twice a year) for the whole repository OR will be queued into batches, such as Collections
- [x] Results are logged to common Preservation Events metadata
- [x] Results can be included in a repository-wide Fixity Check report that indicates how many files were checked, the percentage that successfully passed, and a list of those which failed (separate Epic)
- [x] Event records if fixity checks pass or fail for all files within a given work (or FileSet, if aggregated at the FileSet level)
- [x] If fixity check fails, a record of which specific files failed within a given object is added to the log	

Deferred/Enhancements
* Runs fixity checks on all files in a FileSet (we will start with the PMF in 0.5)
* Is automatically run as part of multiple Preservation Workflows (Ingest, Dissemination, Versioning)
* Provides checking for one or more Curate-generated checksum types (see Epic #210): for v.1, SHA1 only

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
