### ISSUE TITLE
Extract selected work metadata from Alma for books and serials

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#218]
## Story
As a Library Staff Depositor, I want selected Descriptive and other work-level metadata to be extracted from existing Alma records as part of my deposit process, so that metadata that has already been created can be stored and indexed for the repository 

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Relates to #21 (extract from and store DAMS records)
Some of this work will be developed by DCE. For v.1 we will extract metadata from Alma, and in some cases spreadsheets (separate epic). For v.1, we will do a pull-only (metadata edited in the repository is not synched or pushed back to Alma)

Appropriate Alma record IDs are recorded at the work level in pull-list spreadsheets.

#### Links to Additional Information
[Metadata Mapping - MARC/Alma to DLP](https://docs.google.com/spreadsheets/d/1a3fYi5v3oMiujFS4m-2j1ap5EgTueG-7h_gVC9pUluU/edit#gid=1020426242)
Alma publishing directory (link/docs TBD from Core Systems)
[File Mappings and Metadata Extraction Concept](https://docs.google.com/drawings/d/1gV_gpOZauBGaYEvkFaG62IGrWBjY2T-1obY32n0r-NU/edit)
Related epic: Extract Selected Metadata from Pull-Lists

#### Checklist
- [x] The Alma extraction process is integrated/compatible with the larger Curate bulk-ingest method
- [x] The Alma extraction process works with an additional process to extract additional metadata from a pull-list spreadsheet, which supplies the necessary Alma record IDs 
- [x] Selected metadata is mapped for ingest as specified in the Alma/MARC mapping, stored as RDF, and indexed as specified in the Curate generic work model
- [x] Selected metadata to be extracted is additionally transformed as specified in the Alma/MARC mapping document

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
