### ISSUE TITLE
Extract metadata from DAMS export files

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#219]
## Story
As a Library Staff Depositor, I want to supply Descriptive, Administrative, Rights, or Preservation Workflows metadata from a source file that I specify during batch-loading/migration of objects, so that selected metadata can be extracted, stored and indexed as part of the preservation package

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
All work-level metadata (Descriptive, Rights, Administrative, Preservation) for images being ingested from the DAMS workflow will be contained in an export file generated by the DAMS, which will have a common column structure. 

This epic may also be related to Preservation Event for Metadata Extraction (TBD).

#### Links to Additional Information
[DAMS to Curate work metadata mapping](https://docs.google.com/spreadsheets/d/1Mv78t-1HJNPFgBgN6eGt_sM0iumuBkFAFkRP7YhD1Dk/edit#gid=1448411155) - All Fields tab
[File Mappings and Metadata Extraction Concept](https://docs.google.com/drawings/d/1gV_gpOZauBGaYEvkFaG62IGrWBjY2T-1obY32n0r-NU/edit)
Related Epic: Store a copy of DAMS metadata as a supplemental preservation file
Related Epic: Bulk ingest

#### Checklist
- [x] DAMS metadata may be part of manifest file or a standalone CSV as needed
- [x] Extraction process interoperates with bulk-creation of image objects
- [x] Selected metadata fields are extracted and stored as RDF properties according to the DAMS to Curate generic work model mapping
- [x] Selected fields are interpreted as Hyrax/Curate system settings (e.g. Visibility)

Related:
* Extraction outcomes are recording using standard Event metadata, with some additional details for what type of metadata has been extracted

Deferred:
* Preservation Event is associated with an Accession Workflow (if applicable/TBD July development work)

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
