### ISSUE TITLE
Generate preservation workflow and events logs

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#242]
## Story
As a Repository Administrator, Collection Manager or Preservation Curator, I want to to see a detailed preservation workflow and events log that provides information about any human or system-initiated events that have occurred on the object, so that I know routine preservation checks have occurred on an object as expected, and so I can troubleshoot unwanted behavior on an object

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
The repository should generate a comprehensive machine and human readable log of events and workflows applied to an object and its component files. This epic outlines a metadata structure in either RDF or XML to document system activities identified by the Digital Preservation FRG. 

UPDATE: this epic was revised significantly related to the feasibility of capturing events and workflows relative to Hyrax asynchronous processing.

#### Links to Additional Information

[Approved Preservation Events & Workflows](https://wiki.service.emory.edu/display/DLPP/Preservation+Event+and+Workflow+Recommendations)
[Preservation Workflow Metadata properties needed](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=1221411736)
[Preservation Events - General Metadata properties needed](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=497852377)
[Preservation Log - XML-based Mockup](https://drive.google.com/file/d/1osxuTL2rCbu_aasE5xTXIK9pazrSwIN3/view?usp=sharing) - *HOLD for ongoing Hyrax confirmations. May need to revise this significantly.*
[Preservation Log - Sample Event Outputs - RDF based Mockup for Fedora]
(https://docs.google.com/document/d/1O_Ut_j8ZAf9WdMGOUNwreM-WVEZ04rKictnUWg3-BLA/edit#heading=h.smitt5kwdlfq)

#### Checklist

For 0.4, Hyrax-loggable Accession and Ingest Workflow Events are logged

Works
- [x] Policy Assignment (assignment of rights/visibility level)
- [x] Validation (SIP validated and received by Fedora)

Files
- [x] Metadata extraction (files/FITS)
- [x] Format identification (files/FITS)
- [x] Validation (files/FITS)
- [x] Message digest calculation 
- [x] Virus check (if successful: failures may be hard to capture)
- [x] Replication/File Submission

Additional requirements:
- [x] Log is generated as part of the Ingest process, and is compatible with bulk import tools
- [x] Log is generated for an object, but also includes information about the files attached to the object
- [x] Log is system-managed and allows for appending, but not revising prior log entries
- [x] Standard event metadata provided: event name, name of user or process that initiated the Event, start and end date, status such as pass/fail, and repository ids for the object or files the event applied to  
- [x] Event-specific metadata provided: sub-types of actions and details; software used; specific data sources
- [x] Standard workflow metadata can be associated with objects: workflow name, who initiated, start and end date, status such as "complete", rights and notes information  
- [x] Log may document events that occurred outside of a repository context (prior to ingest)
- [x] Selected information from the log may be included in summary views available to Curate users
- [x] Selected information from the log may be indexed for reporting needs (e.g. a report of objects containing files which failed a fixity check or failed validation, or a report of objects which were ingested and made visible due to a certain rights determination)

Deferred to separate epics/future releases:
* Standard workflow metadata can be associated with events in the log: workflow name, who initiated, start and end date, status such as "complete", rights and notes information  (workflows and events are not inter-related yet)
* Metadata extraction (object level, from Curate form, CSV, or Alma) - we don't yet have a way to determine if a work was bulk-created or manually created by form
* Fixity Check [will occur on a schedule or on demand post-ingest]
* Log is encoded as a human readable view or file that can be exported as part of a preservation object for v.1+ versions of Curate
* Log can be viewed, but not directly edited within the Curate UI
* Log may indicate if an event normally run as part of a workflow sequence was skipped 
* Log can be accessed in a read-only capacity through one or more locations in Curate, including Edit Work, but may be restricted to selected users/groups

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by tmiles2** [comment]
Collin did you complete the breakout of this epic?
