### ISSUE TITLE
Event - Virus Check

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#248]
## Story
As a Preservation Curator or Repository Administrator, I want to scan files deposited into the repository for viruses, so that I can be aware of any infected files and take actions to quarantine them

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
We may need to adapt this based on what Hyrax does as part of its virus check, quarantine, and unquarantine process.

#### Links to Additional Information
[Approved Preservation Events & Workflows](https://wiki.service.emory.edu/display/DLPP/Preservation+Event+and+Workflow+Recommendations)
[Sample Events Data](https://docs.google.com/document/d/1O_Ut_j8ZAf9WdMGOUNwreM-WVEZ04rKictnUWg3-BLA/edit#heading=h.smitt5kwdlfq)

#### Checklist
- [x] record standard events/workflow metadata in the preservation log	
- [x] record whether or not the files of a digital object pass the virus check in the preservation log
- [x] run as part of the Accessioning or Ingest workflow (depending on Hyrax sequence)	
- [x] run on demand or as part of Curate's deposit steps	

Deferred as enhancements, based on current Hyrax capabilities:
- [ ] run on demand 
- [ ] runs on ALL files in a FileSet	
- [ ] if a virus is detected, system should place the object and files in quarantine and not complete the ingest [DISCUSS vs Hyrax behavior. Do we quarantine the whole object or just skip the infected file?]
- [ ] if a virus is detected, the system should log which files contained a virus
- [ ] if virus detected, the software should attempt to clean the digital object’s files

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
