### ISSUE TITLE
Event - Policy Assignment for Access Control/Visibility Settings

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#249]
## Story
As a Library Staff Depositor or Collection Manager, I want to ensure that Policy Assignment events are logged when visibility and access levels are recorded as part of our preservation log, so that application of Emory policies is formally documented and preserved with the object

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Add notes here

#### Links to Additional Information
[Approved Preservation Events & Workflows](https://wiki.service.emory.edu/display/DLPP/Preservation+Event+and+Workflow+Recommendations)
[Sample Event Outputs](https://docs.google.com/document/d/1O_Ut_j8ZAf9WdMGOUNwreM-WVEZ04rKictnUWg3-BLA/edit#heading=h.juxwhjivu8xe)

#### Checklist
- [x] Event is logged at the work level
- [x] Outcomes are stored using standard events metadata
- [x] Occurs as part of the Accession/Ingest workflow

Deferred:
* Whenever an object's visibility is changed, this activity is recorded as a Policy Assignment Event
* The new visibility state is recorded as part of the Event detail

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
