### ISSUE TITLE
Event - Format Identification

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#250]
## Story
As a Preservation Curator, I want to use Format Identification service such as FITS and see its outputs as Technical Metadata or a supplemental file, so that I can determine file format and version information for files within a digital object

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Relates to separate epics/enhancements: #208 for Metadata Extraction Event

#### Links to Additional Information
[Approved Preservation Events & Workflows](https://wiki.service.emory.edu/display/DLPP/Preservation+Event+and+Workflow+Recommendations)
[Preservation - Metadata Properties Needed](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=497852377)
[File & FileSet/Technical Metadata](https://docs.google.com/spreadsheets/d/1csDcDnJdhB1VLlgJUU95DndXSeIP2j8yPMlErrsVVPw/edit#gid=1836172006)
[List of all Preservation UI Mockups](https://docs.google.com/document/d/1z8sa020Kj4NJvreVGxxEWnXV_NGdAjUJQdMz3sRbDk8/edit#heading=h.lheatu9c6eeg)

#### Checklist
- [x] Event outcomes should be recorded in the Preservation Log using standard events/workflow metadata	
- [x] Selected metadata is indexed for staff use [EPIC TBD]	
- [x] If identification fails: record which files failed and record no format identified; notify staff depositors of the failure. self-depositors should not be notified	
- [x] Record which tool was used for format identification	
- [x] Record which format was identified for each file	
- [x] Can be run as part of an Accession or Ingest workflow
- [x] May be associated with additional workflows in future releases
- [x] May be run on demand outside of a workflow

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
This may require enhancement in the future as it is unclear what will trigger a failure.
