### ISSUE TITLE
Event - Format Validation

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#252]
## Story
As a Library Staff Depositor,Collection Manager or Preservation Curator, I want to use a Validation service and logging for ingested files, so that I can be notified if a file I deposited is potentially corrupted and needs to be replaced

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Relates to FITS characterization process; logs FITS' format validation outcome as its own event. FITS defines format validation as "Determination of a file's consistency with the requirements of the specification(s) governing the file's format."

#### Links to Additional Information
[FITS Filestatus section](https://projects.iq.harvard.edu/fits/fits-xml#filestatus)
[Approved Preservation Events & Workflows](https://wiki.service.emory.edu/display/DLPP/Preservation+Event+and+Workflow+Recommendations)
[Preservation - Metadata Properties Needed](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=497852377)
[Preservation Log - XML Mockup](https://drive.google.com/file/d/1osxuTL2rCbu_aasE5xTXIK9pazrSwIN3/view?usp=sharing)
[File & FileSet/Technical Metadata](https://docs.google.com/spreadsheets/d/1csDcDnJdhB1VLlgJUU95DndXSeIP2j8yPMlErrsVVPw/edit#gid=1836172006)
[List of all Preservation UI Mockups](https://docs.google.com/document/d/1z8sa020Kj4NJvreVGxxEWnXV_NGdAjUJQdMz3sRbDk8/edit#heading=h.lheatu9c6eeg)
[UI Mockup: Preservation Summary - Event Failure](https://docs.google.com/drawings/d/1nhAGybwsZj4av06ZH-2je6d1yoXsNZLMc5C4NJ3DYfM/edit)

#### Checklist
- [x] Run as part of Accession or Ingest workflow
- [x] Can be run on demand outside of a workflow
- [x] Event outcomes stored in Preservation Log including standard Event metadata
- [x] Log FITS validation with the type, "Format validation" (in the future, other types of validation may occur)
- [x] A failure should not prevent a file from getting deposited 

Optional/related features:
* If there is a failure, provide either a UI-based notification or an email to the depositor

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
For implementation purposes, Format Identification, Format Validation, and Technical Metadata extraction were combined into a single event log called Characterization.
