### ISSUE TITLE
Bulk ingest method for Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#273]
## Story
As a Library Staff Depositor, I want to create objects/metadata in bulk through a spreadsheet or other means, so that I can ingest related objects more quickly and reduce redundant data entry

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic describes an enhanced bulk-ingest process that will be developed for Phase 1 Migrations, with a goal of re-usability and extension to future migrations. Emory libraries staff depositors will need a customized bulk-ingest method to create complex objects supporting our Archival Information Package structure. 

#### Links to Additional Information
[Curate Generic Work: SIP Mapping Template](https://docs.google.com/spreadsheets/d/1Qy7MOrrpaQrVhepDdHlDxgQ0_8wpB_YMYude5M-J_Ho/edit#gid=403514438)
[Data Sources for Phase 1 Migrations](https://drive.google.com/open?id=1hYrFx2UI1nSeN9crDSlmu8F-hdminztD)
[DAMS metadata mapping (images)](https://docs.google.com/spreadsheets/d/1Mv78t-1HJNPFgBgN6eGt_sM0iumuBkFAFkRP7YhD1Dk/edit#gid=1448411155)
[Alma/MARC metadata mapping (books)](https://docs.google.com/spreadsheets/d/1a3fYi5v3oMiujFS4m-2j1ap5EgTueG-7h_gVC9pUluU/edit#gid=1020426242)
[Pull-list mapping (books)](https://docs.google.com/spreadsheets/d/1c-P_KybzJZ9s9J1KCemeFiUsUfS23FrDfHD-WyegEA4/edit#gid=1808149743)

#### Checklist
- [x] Bulk-ingest may be initiated and monitored through a user interface within Curate
- [x] Bulk-ingest UI reports errors as part of the pre-check process (additional error reporting handled by the Curate/Cor environment)
- [x] Bulk ingest will assign or inherit appropriate Depositor and Manager role permissions from the Collection it is deposited into
- [x] Bulk-ingest method creates multiple objects in batch according to standardized, user-supplied pull-lists 
- [x] Bulk-ingest method assigns objects to a specified collection in Curate 
- [x] Bulk-ingest method maps files to the Curate generic work model, assigning their appropriate FileSet context and PCDM use according to supplied structural metadata 
- [x] Bulk-ingest method extracts metadata from one or more input sources as specified in the SIP mappings for each collection, including spreadsheets and Alma records
- [x] Bulk ingest method extracts, maps, and stores selected metadata as RDF properties in the Curate generic work model as specified in the DAMS, Alma, and pull-list metadata mappings
- [x] Bulk-ingest method integrates with/interoperates with with an Emory supported file transfer process
- [x] Bulk-ingest method integrates with/interoperates with fixity checking process for pre-ingested,  uploaded files
- [x] Bulk-ingest method integrates with Curate's preservation events and logging

Deferred:
* Bulk-ingest method may also extract and store metadata as part of an XML Preservation Log from one or more sources as specified in the SIP mappings for each collection
* Bulk-ingest method supports both flat and nested work structures

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Final testing is needed for assignment of collection permissions on objects. Unable to confirm with Langmuir batch, because curate-arch collections did not have correct permissions.
