### ISSUE TITLE
Assign non-Administrator Roles, Groups and Users to Curate Collections

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#275]
## Story
As a Repository Administrator, I want to assign system-wide user roles to groups for Administrative Sets and Collections, so that I can assign and manage individual user permissions effectively

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic relates to configuring Curate user accounts for Library Staff, and managing those users in Hyrax permission groups assigned as Participant Roles for each collection. Generally, permission groups/roles are established for each Library and are re-used across the collections. We have also identified one or more repository-wide groups that should have access to all Collections, but users in this group will not need full Administrator-level access.

#### Links to Additional Information
[Groups and Users worksheet](https://docs.google.com/spreadsheets/d/1vdercM6W3FZjHCjim0qyvPnlRo9tgbvY7XQ0SiDhx4o/edit#gid=1791455727)
[Curate/Hyrax System Roles: best practices](https://docs.google.com/document/d/121IwZC43YWnGpWZqVtLl_ezhX4V1y4EqJvfP56ztsaI/edit#)

#### Checklist
- [x] Identified Library Staff users from the worksheet above have Curate accounts
- [x] Identified groups of users are created within Curate
- [x] Appropriate groups have been assigned to Participant Roles for each collection (e.g. Viewer, Depositor, and Manager level roles)
- [x] Hyrax-default roles/users are removed from each Collection
- [x] Permissions structure is compatible with any setup/automation tasks for Curate

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Some additional testing will be needed when we wipe and restore production, but initial configurations and testing are complete.
