### ISSUE TITLE
Store Alma MARC XML files as part of preservation package for books/serials

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#285]
## Story
As a Collection Manager, Preservation Curator, I want to store a static copy of a metadata record along with the digital object, so that I can provide additional domain specific metadata that may not be supported by the repository's RDF mappings

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic is related to the Alma extraction process. When metadata is extracted from Alma MARC XML records, we also want to keep a copy of the XML file and store it as a binary in the preservation package along with other files.

#### Links to Additional Information
Related epic #218: Extract metadata from Alma records
[File Mappings and Metadata Extraction Concept](https://docs.google.com/drawings/d/1gV_gpOZauBGaYEvkFaG62IGrWBjY2T-1obY32n0r-NU/edit)
SIP Mapping - Yellowbacks/Kirtas
SIP Mapping - Yearbooks/Kirtas
SIP Mapping - Yearbooks/LIMB

#### Checklist
- [ ] The MARC XML binary file is retained and attached as a Preservation Master file use to a new FileSet, which is categorized as Supplemental Content
- [ ] A copy of the MARC XML record is presented to end users as a Supplemental Content File 
- [ ] Appropriate file-oriented Preservation Events (e.g. Message Digest Calculation, Format Identification, Validation, Virus Check) should be run on the MARC XML file when it becomes part of the object package
- [ ] For nested works which share an Alma record, the MARC XML file is attached to the parent object only

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Discussed de-scoping this work with DCE. As an alternative, we can package up the full XML export from Alma and add it to a collection's administrative object, like we are doing with DAMS exports.
