### ISSUE TITLE
Generate file manifests for Curate bulk ingest - DAMS images

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#287]
## Story
As a Library Staff Depositor, I want to generate a Curate-readable structural metadata ingest file based on outputs from the DAMS digitization workflow, so that I can create complex image objects in a bulk ingest process

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
In order to bulk-ingest image objects, we need to generate a normalized source file (e.g. CSV) to map legacy files to the Curate generic work model, which permits multiple files/derivatives per FileSet, and multiple categories of FileSets. The digitization team's workflow for digitized and born digital images DAMS utilizes a file and directory naming scheme and file path information stored in metadata that can be used to help generate the file mappings needed for Langmuir and the other image collections for Phase 1 migration.

#### Links to Additional Information
[CSV template for file manifest/filemapping structure](https://docs.google.com/spreadsheets/d/1TNT3Bw6lq2BakJBaUiLRy8BCot3CsMF1gaBIctQlAy4/edit#gid=0)
[Combined SIP mapping for DAMS images](https://docs.google.com/spreadsheets/d/1GvIt9Cqjvh_64ghV0fwl3xc7_cVSYqqepzF8RwYnARY/edit#gid=403514438)
[SIP mapping for Langmuir](https://docs.google.com/spreadsheets/d/1SBfJKv_sHQSBVj462jLNYU0LuqOZ9v7L_yIt2r6DeHM/edit#gid=403514438)
[SIP mapping for Kobe](https://docs.google.com/spreadsheets/d/1oQav9TKGLYnCmKbRq5y_-zqWyQIthRz2P7z4-KL-YIU/edit#gid=1445102745)
[SIP mapping for Medical Artifacts](https://docs.google.com/spreadsheets/d/1Gii4l71_ZwZWcD_UyZgMJ01YtvVTmkhCN9Ip8vt8Qds/edit#gid=1066055121)
[DAMS Filenaming and ordering notes](https://docs.google.com/document/d/1n66diSkAYMoPRbI6qvSucdTNtPGK2z-H_3PEdWf17TQ/edit#)
[Data Sources for Phase 1 Migrations](https://drive.google.com/open?id=1hYrFx2UI1nSeN9crDSlmu8F-hdminztD)
Related epic #273: bulk ingest process
See also separate epics for specific collections' ingests.

#### Checklist
- [x] Interoperates with/supports larger bulk ingest process to support bulk creation of Curate works
- [x] Assigns files to their appropriate preservation context using the DAMS SIP mapping linked above
- [x] Image objects may be multi-part (front/back or multiple views of a physical object)
- [x] Image objects are ordered according to their file naming convention
- [x] Labels for FileSets can be automatically generated using the part number in the filename
- [x] Image objects' file mappings associate a file with a collection
- [x] Image objects' file mappings associate a file with a work
- [x] Image objects' file mappings associate a file with a FileSet and its context (primary content/supplemental content/supplemental preservation)
- [x] Image objects' file mappings associate a file with a use within a FileSet (Preservation Master, Intermediate File, Service File etc.)

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Closing based on acceptance testing for Langmuir; additional work may be needed for non-Langmuir collections but that is beyond the scope of our work with DCE.
