### ISSUE TITLE
Create Curate works and attach book files from digitization workflow outputs

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#288]
## Story
As a Library Staff Depositor, I want to batch-ingest book objects generated from multiple book digitization workflows using a supplied file mapping, so that I can create complex book objects in bulk

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
The bulk-ingest method should read from a normalized structural metadata source file to create objects mapped to the Curate generic work model (see epic #289). This epic focuses on the creation of complex objects based on supplied file manifests mapped to the Curate generic work model, which permits multiple files/derivatives per FileSet, and multiple categories of FileSets. 

#### Links to Additional Information
Related epic #273: bulk ingest process
Related epic ###: generate file manifests for Curate bulk ingest: books
Related: file transfer
Pull-lists

#### Checklist
- [x] As part of the larger bulk ingest process, objects are created in bulk from a supplied book object and file mapping manifest
- [x] Files are retrieved from a designated upload directory and copied to permanent storage
- [x] Files are attached to batch-created works and assigned to their appropriate preservation context using the LIMB or Kirtas SIP mapping
- [x] Book objects generated can be either flat (single-volume) or nested (multiple volumes attached to a parent work)
- [x] Book objects generated are assigned to a primary collection entity in Curate
- [x] Book objects generated are assigned to a primary Admin Set entity in Curate
- [x] Book objects generated in batch can be opened and edited using the Curate edit work form
- [x] Interoperates with related metadata extraction processes (extract from Alma, extract from pull-list)
- [x] Creation of objects and assignment of files interoperates with standard Curate preservation events and workflows and logging

QA testing
- [x] If Emory's environment does not generate thumbnails as expected for PDFs, we should accept based on DCE's environment demos

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Closing, but see bug ticket for LIMB SIP mapping for METS files #855
