### ISSUE TITLE
Generate file manifests for Curate bulk ingest - books 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#289]
## Story
As a Library Staff Depositor, I want to generate a Curate-readable structural metadata ingest file based on outputs from the LIMB and Kirtas digitization workflows, so that I can create complex book objects in a bulk ingest process

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
The library has used different book digitization software and workflows over time, which has produced distinct file outputs. Books are also stored in different NAS directories and may use different conventions. In order to facilitate a bulk-ingest process to create complex book objects and attach files to FileSets and assign correct file uses, we need to produce a consistent input source file that Curate can read from. Curate SIP mappings for two book digitization workflows are linked below.

#### Links to Additional Information
[CSV FileSet manifest template idea](https://docs.google.com/spreadsheets/d/1TNT3Bw6lq2BakJBaUiLRy8BCot3CsMF1gaBIctQlAy4/edit#gid=0)
[LIMB digitization workflow SIP mappings - single/multi volume](https://docs.google.com/spreadsheets/d/1FuzvRrBzQQoKERnFAY_dSN8VgXiEHIjUclqSturN0y8/edit?usp=sharing)
[Kirtas digitization workflow SIP mappings  - single/multi volume](https://drive.google.com/open?id=1mHeyHFO57mxAan6E7mhaEpIRg4IF62g1LpjSbJhe_sg)
[Digitized Books pull-list to Curate metadata mapping](https://docs.google.com/spreadsheets/d/1c-P_KybzJZ9s9J1KCemeFiUsUfS23FrDfHD-WyegEA4/edit#gid=1808149743)
TBD: Additional notes about naming, ordering etc.
See also related epics/info for specific collections' ingest (Yellowbacks, Yearbooks)

#### Checklist
- [x] Book objects may be flat (single volume) or nested (multiple volumes per work)
- [x] Book objects' file mappings associate a file with a collection
- [x] Book objects' file mappings associate a file with a work
- [x] Book objects' file mappings associate a file with a FileSet and its context (primary content/supplemental content/supplemental preservation)
- [x] Book objects' file mappings associate a file with a use within a FileSet (Preservation Master, Intermediate File, etc.)
- [x] Book objects files are mapped to the Curate generic work model using the Kirtas or LIMB SIP mappings linked above, as appropriate for the collection
- [x] Manifest file interoperates with additional metadata extraction processes (extract from/store a copy of Alma MARC XML; extract from pull-list)
- [x] Manifest file may be merged with, or work in tandem with the digitized book collections pull-lists

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Closing but see revision ticket #855 for LIMB SIP mapping
