### ISSUE TITLE
Create Curate works and attach image files from DAMS workflow

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#291]
## Story
As a Library Staff Depositor, I want to batch-ingest book objects generated from digitization or digital photography workflows using a supplied file mapping, so that I can create complex image objects in bulk

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
The bulk-ingest method should read from a normalized structural metadata source file to create objects mapped to the Curate generic work model (see epic # 287). This epic relates to the creation of complex objects based on mapping files to the Curate generic work model, which permits multiple files/derivatives per FileSet, and multiple categories of FileSets.

#### Links to Additional Information
Add [links](https://www.emory.edu/) here
[File Mappings and Metadata Extraction Concept](https://docs.google.com/drawings/d/1gV_gpOZauBGaYEvkFaG62IGrWBjY2T-1obY32n0r-NU/edit)
Data Sources for Phase 1 Migrations

#### Checklist
- [x] As part of the larger bulk ingest process, objects are created in bulk from a supplied DAMS object and file mapping manifest
- [x] Files are retrieved from a designated upload directory and copied to permanent storage if needed 
- [x] Image objects generated are assigned to a primary collection entity in Curate
- [x] Image objects generated are assigned to a primary Admin Set entity in Curate  
- [x] Image objects generated are multi-part and may contain multiple FileSets (but are not expected to be nested works)
- [x] Files are attached and assigned to their appropriate preservation context using the DAMS SIP mapping
- [x] Files attached and assigned may also follow more specific mappings if needed; defined in separate epics  
- [x] Interoperates with related metadata extraction processes (extract from/store a copy of DAMS metadata)
- [x] Creation of objects and assignment of files interoperates with standard Curate preservation events and workflows and logging

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Closing this epic based on acceptance testing for Langmuir batch 5 in curate-arch.
