### ISSUE TITLE
FileSet Management UI Enhancements

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#349]
## Story
As a Library Staff Depositor, I want to manage related sets of files using the Curate interface, so that I can manage display properties and perform file management on works that have already been deposited

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic includes some UI enhancements deferred from 0.3 epics #119 and #127.

#### Links to Additional Information
Add [links](https://www.emory.edu/) here

#### Checklist
- [ ] Provide navigation to edit/manage individual Files or FileSets through the standard Hyrax File Manager, such as changing visibility or Sharing permissions for a specific file or FileSet (deferred from #119)
- [ ] Ability to see all the FileSets attached to a work, and navigate to options to manage the fileset as a whole
- [ ] Change Visibility settings on a FileSet that has been attached to a work
- [ ] Assign or adjust the display order of FileSets in a work for Lux (deferred from #119)
- [ ] Assign the default Thumbnail for the set (deferred from #119)
- [ ] Delete a FileSet from a work while creating a work (but at least one FileSet needs to exist)

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
closing as duplicate
