### ISSUE TITLE
Migrate Langmuir Collection

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#350]
## Story
As a Collection Manager, I want to ingest the Langmuir digital collection, so that I can provide long-term access to the material in a preservation repository

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Add notes here

#### Links to Additional Information
[Langmuir migration strategy document](https://emory.box.com/s/1ri08txiy14v8m9vvjd3spf7rf5jw19w)
[General acceptance criteria for Phase 1 Migrations](https://emory.box.com/s/8jqlpyoggpr2wxsyuysx1y5z4b09hr3d)
Langmuir metadata (pre-processed) - [GitHub](https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/2019/in_development/langmuir)
[DAMS system - file naming and ordering conventions](https://docs.google.com/document/d/1n66diSkAYMoPRbI6qvSucdTNtPGK2z-H_3PEdWf17TQ/edit)
[QA test log](https://docs.google.com/spreadsheets/d/1Gj9AuNX46THLh6d2FgyFsrFyK8wayREuE2gNaGFiBPA/edit#gid=108442089)

#### Checklist
- [x] Langmuir Collection entity includes all supplied metadata
- [x] Langmuir Collection entity and its works are assigned the [designated Rose Library and repository-wide Participant groups](https://docs.google.com/spreadsheets/d/1vdercM6W3FZjHCjim0qyvPnlRo9tgbvY7XQ0SiDhx4o/edit#gid=0) at time of ingest in order to propagate Curate Edit/Sharing permissions
- [x] All populated Descriptive, Rights, and Administrative metadata fields supplied in the CSV are migrated and mapped to the Curate work model
- [x] Additional Preservation Workflows metadata is mapped to works generated by the import tool [can occur post-ingest if needed]
- [x] Number of works expected: 12,664
- [x] Number of Files expected: 45,640
- [x] Number of FileSets expected: 22820
- [x] Works and FileSets are generated according to the [Langmuir SIP mapping](https://docs.google.com/spreadsheets/d/1GvIt9Cqjvh_64ghV0fwl3xc7_cVSYqqepzF8RwYnARY/edit#gid=403514438)
- [x] FileSets are categorized using Emory categories (items are assigned to Primary Content)
- [x] FileSets are attached to support images with Fronts and Backs of selected images
- [x] FileSets are attached to support images with for Fronts only (selected objects)
- [x] Support for creation of multiple views of selected objects (not fronts/backs) [this could be done manually also]
- [x] FileSets are ordered using the part number from the filename convention
- [x] FileSets are labelled using a Front/Back convention, or Part number for images not following front and back convention
- [x] Custom access controls are assigned to the works to restrict file quality and/or download as identified
