### ISSUE TITLE
Migrate Yellowbacks Collection

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#351]
## Story
As a Collection Manager, I want to ingest the Yellowbacks digital collection, so that I can provide long-term access to the material in a preservation repository

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Add notes here

#### Links to Additional Information
[Yellowbacks/Kirtas Workflow SIP mapping](https://docs.google.com/spreadsheets/d/1mHeyHFO57mxAan6E7mhaEpIRg4IF62g1LpjSbJhe_sg/edit#gid=2106334426)
[Yellowbacks migration strategy document](https://emory.box.com/s/5upieko3z95fjnhiayo029p8hya4lv2p)
General acceptance criteria for Phase 1 Migrations
[Books Metadata: CSV and Alma](https://docs.google.com/spreadsheets/d/1g7jYZ3hIjsEgqWbIpyLjVT7q9gNrDiyz_Aevhqd97xs/edit#gid=481364733)
[Yellowbacks CSV metadata - GitHub](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yellowbacks_pull_list_Curate.csv)
[Alma metadata - GitHub](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/DLP_Publishing_Test_20190919.xml)
Yellowbacks QA test plan- in development

#### Checklist
- [ ] Yellowbacks' works structure consists of parent work, volume(s), and pages
- [ ] Yellowbacks Collection entity includes all supplied metadata (from spreadsheet or entered via Curate form)
- [ ] Yellowbacks Collection entity and its works are assigned to the [designated Rose Library and repository-wide Participant groups](https://docs.google.com/spreadsheets/d/1vdercM6W3FZjHCjim0qyvPnlRo9tgbvY7XQ0SiDhx4o/edit#gid=0) at time of ingest
- [ ] Number of works expected: 1,232
- [ ] Number of Files expected: 1,408,404
- [ ] Number of FileSets expected: ~417,070 (page FileSets + additional volume-level FileSets for PDFs, MARC records, OCR files)
- [ ] Works and FileSets are generated according to the [Kirtas/Yellowbacks SIP mapping](https://docs.google.com/spreadsheets/d/1mHeyHFO57mxAan6E7mhaEpIRg4IF62g1LpjSbJhe_sg/edit#gid=732175628)
- [ ] FileSets are categorized using Emory AIP categories (FileSets are variably assigned to Primary Content, Supplemental Content, or Supplemental Preservation File categories)
- [ ] Per the SIP mapping above, work or volume-level files to migrate are PDFs, MARCXML records, OCR XML files
- [ ] Per the SIP mapping above, page-level files to migrate are .TIF, .POS, .TXT
- [ ] Book objects support nested objects such as parent work with multiple child volumes or copies
- [ ] Works are assigned to standard Access Controls/visibility as indicated in spreadsheets
- [ ] All populated Descriptive, Rights, and Administrative metadata fields supplied in the CSV are migrated and mapped to the Curate work model
- [ ] Additional metadata fields are extracted from Alma metadata
- [ ] Zero-byte files produced by digitization software should not be treated as software errors, if they do not attach
- [ ] Additional Preservation Workflows metadata is mapped to works generated by the import tool [can occur post-ingest if needed]

Deferred:
* Copies of the MARC XML record are attached to each work according to the SIP mapping [can defer as enhancement if needed]

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Closing this because we learned after the fact it is not achievable to migrate this collection as quickly as the others in Phase 1, and we will be ingesting these ongoing for a long time.
