### ISSUE TITLE
Migrate Emory Yearbooks Collection

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#352]
### Story

As a Collection Manager, I want to ingest the Emory Yearbooks digital collection, so that I can provide long-term access to the material in a preservation repository

### Acceptance Criteria

Use one or more of the following options to provide acceptance criteria.

#### Notes

Add notes here

#### Links to Additional Information

[Yearbooks/Kirtas Workflow SIP mapping](https://docs.google.com/spreadsheets/d/1mHeyHFO57mxAan6E7mhaEpIRg4IF62g1LpjSbJhe_sg/edit#gid=2106334426)
[Yearbooks/LIMB Workflow SIP mapping - selected volumes redigitized in 2019](https://docs.google.com/spreadsheets/d/1FuzvRrBzQQoKERnFAY_dSN8VgXiEHIjUclqSturN0y8/edit#gid=1778518181)
Yearbooks migration strategy document
General acceptance criteria for Phase 1 Migrations
[Books Metadata: CSV and Alma](https://docs.google.com/spreadsheets/d/1g7jYZ3hIjsEgqWbIpyLjVT7q9gNrDiyz_Aevhqd97xs/edit#gid=481364733)
[Yearbooks CSV metadata: Kirtas - GitHub](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yearbooks/EU-Yearbooks-Curate-Kirtas.csv)
[Yearbooks CSV metadata: LIMB - GitHub](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yearbooks/EU-Yearbooks-Curate-LIMB.csv)
[Yearbooks Alma metadata - GitHub](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yearbooks/alma-yearbooks.xml)
Yearbooks QA test plan- in development

#### Checklist

- [x] Yellowbacks' works structure consists of parent work, volume(s), and pages
- [x] Yellowbacks Collection entity includes all supplied metadata (from spreadsheet or entered via Curate form)
- [x] Yellowbacks Collection entity and its works are assigned to the designated Rose Library and repository-wide Participant groups at time of ingest
- [ ] Number of works expected: 137
- [ ] Number of Files expected: 131139
- [ ] Number of FileSets expected: ~ (page FileSets + additional volume-level FileSets for PDFs, MARC records, OCR files, METS files)
- [ ] Works and FileSets are generated according to the Kirtas/Yearbooks SIP mapping
- [ ] Selected Works and FileSets are generated according to the LIMB/yearbooks SIP mapping
- [ ]  FileSets are categorized using Emory AIP categories (FileSets are variably assigned to Primary Content, Supplemental Content, or Supplemental Preservation File categories)
- [ ] Per the SIP mappings above, work or volume-level files to migrate are PDFs and OCR XML files or METS XML files, depending on the digitization workflow
- [ ] Per the SIP mappings above, page-level files to migrate are .TIF, .POS/.XML, .TXT depending on the digitization workflow
- [ ] Book objects support nested objects such as parent work with multiple child volumes or copies
- [ ] Works are assigned to standard Access Controls/visibility as indicated in spreadsheets
- [ ] All populated Descriptive, Rights, and Administrative metadata fields supplied in the CSV are migrated and mapped to the Curate work model per the CSV mapping above
- [ ] Additional metadata fields are extracted from Alma per the Alma mapping above
- [ ] Zero-byte files produced by digitization software should not be treated as software errors, if they do not attach
 
Deferred:
* Copies of the MARC XML record are attached to each work according to the SIP mapping [can defer as enhancement if needed]
* Additional Preservation Workflows metadata is mapped to works generated by the import tool [can occur post-ingest if needed]

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
QA and tracking have occurred over a long period of time in our ingest tracker worksheets.
