### ISSUE TITLE
Migrate Oxford Yearbooks Collection

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#353]
## Story
As a Collection Manager, I want to ingest the Emory Yearbooks digital collection, so that I can provide long-term access to the material in a preservation repository

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
See the Emory Yearbooks epic for additional information.

#### Links to Additional Information
[Yearbooks/LIMB Workflow SIP mapping - selected volumes redigitized in 2019](https://docs.google.com/spreadsheets/d/1FuzvRrBzQQoKERnFAY_dSN8VgXiEHIjUclqSturN0y8/edit#gid=1778518181)
Yearbooks migration strategy document
General acceptance criteria for Phase 1 Migrations
[Books Metadata: CSV and Alma](https://docs.google.com/spreadsheets/d/1g7jYZ3hIjsEgqWbIpyLjVT7q9gNrDiyz_Aevhqd97xs/edit#gid=481364733)
[Oxford Yearbooks CSV metadata: LIMB - GitHub](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yearbooks/Yearbooks-Oxford-Curate-LIMB.csv)
[Yearbooks Alma metadata - GitHub](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yearbooks/alma-yearbooks.xml)
Yearbooks QA test plan- in development

#### Checklist
- [x] Yearbooks' works structure consists of parent work, volume(s), and pages
- [x] Yearbooks Collection entity includes all supplied metadata (from spreadsheet or entered via Curate form)
- [x] Yearbooks Collection entity and its works are assigned to the designated Rose Library, Oxford Library and repository-wide Participant groups at time of ingest
- [ ] Number of works expected: 
- [ ] Number of Files expected: 
- [ ] Number of FileSets expected: ~ (page FileSets + additional volume-level FileSets)
- [x] Works and FileSets are generated according to the LIMB Yearbooks SIP mapping
- [x]  FileSets are categorized using Emory AIP categories (FileSets are variably assigned to Primary Content, Supplemental Content, or Supplemental Preservation File categories)
- [x] Per the SIP mapping above, work or volume-level files to migrate are PDFs, METS files
- [x] Per the SIP mapping above, page-level files to migrate are .TIF, .XML, .TXT
- [x] Book objects support nested objects such as parent work with multiple child volumes or copies
- [x] Works are assigned to standard Access Controls/visibility as indicated in spreadsheets
- [x] All populated Descriptive, Rights, and Administrative metadata fields supplied in the CSV are migrated and mapped to the Curate work model per the CSV mapping
- [x] Additional metadata fields are extracted from Alma per the Alma mapping
- [x] Zero-byte files produced by digitization software should not be treated as software errors, if they do not attach
 
Deferred:
* Copies of the MARC XML record are attached to each work according to the SIP mapping [can defer as enhancement if needed]
* Additional Preservation Workflows metadata is mapped to works generated by the import tool [can occur post-ingest if needed]

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
