### ISSUE TITLE
Configure Emory Libraries Collection Type for Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#383]
## Story
As a Repository Administrator or Collection Manager, I want to configure Collection Types needed for a multi-Library shared repository, so that we can begin assigning Curate user permissions, Collection settings, and populating content in collections

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
For v.1 we will provision a single Collection Type called "Library Collection" that all migrating collection instances will be built from.

#### Links to Additional Information
[Emory Collection Type Specs](https://docs.google.com/document/d/1w0iRk6TfawMWTKxiqHBUWpB5rRtqzcerNl55t5IYplg/edit?usp=sharing)
[Samvera KB: Collections and Admin Sets](https://samvera.github.io/collection-overview.html)

#### Checklist
(See the above Spec document for more details)

- [x] Collection Type is named "Library Collection"
- [x] Nesting is enabled
- [x] Branding is enabled
- [x] Discovery is enabled
- [x] Sharing is enabled
- [x] Apply to New Works is enabled
- [x] Multiple Membership is **disabled**
- [x] Participants: **remove** Registered Users group from Creators role
- [x] This Collection Type will be generated when the application is rebuilt/restored

**Comment by eporter23** [comment]
@bess as we just discussed - here's a screenshot of the UI-configured Collection Type showing the Participants settings:

![Screen Shot 2019-08-09 at 9.45.18 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/274c6446-a521-4e12-ae3d-3678a49201f7)

https://curate.library.emory.edu/admin/collection_types/3/edit?locale=en#participants

**Comment by tmiles2** [comment]
@eporter23 same with this one, should we add it to the release testing document?
