### ISSUE TITLE
Group related sections of metadata fields for editing and export purposes

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#40]
## Story
As a Metadata Specialist/Collection Manager/Library Staff Depositor, I want to group related repository metadata fields for objects into sections, so that they can be presented in groups of related fields in an editing form or could be exported into different individual files for preservation

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Preservation Events and Workflows metadata will be addressed separately, and may be a distinct UI component. 

The acceptance criteria for form UI preferences were provided by the Preservation Metadata Repository Group.

#### Links to Additional Information
[Mockup: form groupings, headings and specific field order - Option D tab](https://docs.google.com/spreadsheets/d/1iebjgAbM5h_KsKj4Ohlqr9hVbIuxiaaBlH2G5p6qhDk/edit#gid=1724787708)
[Mockup: form groupings, headings, layout notes](https://drive.google.com/open?id=191E3wdVWo32fxrL55sKPhH_cE-irNIgo)
[Metadata Implementation Worksheet](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=514733824)

#### Checklist
- [ ] Metadata fields can be grouped into sections and presented visually in the Hyrax create/edit form grouped under headings, accordions, or tabs, corresponding to "Descriptive", "Rights", "Administrative" 
- [ ] Metadata fields are grouped under headings in the following order 1) Descriptive, 2) Rights 3) Administrative 
- [ ] Selected Descriptive fields (required and optional) are visible at all times, while the remainder of Descriptive fields have visibility that can be toggled on or off
- [ ] Rights and Administrative fields are all visible, whether they are required or not
- [ ] Metadata fields are ordered as shown in the [spreadsheet mockup - Option D tab](https://docs.google.com/spreadsheets/d/1iebjgAbM5h_KsKj4Ohlqr9hVbIuxiaaBlH2G5p6qhDk/edit#gid=1724787708)
- [ ] Metadata fields can be logically grouped for export as separate metadata files in future Curate releases (e.g. descriptive.xml, rights.xml, administrative.xml)
- [ ] Metadata fields can be logically grouped for export as files differently than they are presented in a form context, if necessary to meet an external standard

**Comment by eporter23** [comment]
This is basically "ready", but I don't know if we want to introduce another grouping for "Identifiers".

**Comment by eporter23** [comment]
I confirmed groupings of fields for Descriptive, Rights, Administrative with metadata stakeholders on 1/30 - will update the worksheet accordingly.

**Comment by eporter23** [comment]
Changed to 0.3 after software engineering reviewed.
