### ISSUE TITLE
Preview Work Metadata - Enhancements

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#462]
## Story
As a Library Staff Depositor or Collection Manager, I want to preview metadata supplied for works, so that I can see metadata without having to edit the work and in order to anticipate how the metadata will display for Lux 

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Deferred items from co-sprint with DCE.

#### Links to Additional Information
Add [links](https://www.emory.edu/) here

#### Checklist
- [x] Fields are displayed in the same order as identified for the create/edit form (see Form Order column)
- [ ] View work page does not display any fields that are categorized in the Displays To column as Staff Only
- [x] View work page displays all fields that have been populated for a work which are categorized as Displays To: End Users and Staff
- [x] [Filtered view of fields to add to View Work display](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589&fvid=1722653369)

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
This work was largely completed; any remaining work will be a future enhancement.
