### ISSUE TITLE
FileSets Editing UI (v.1)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#482]
## Story
As a Library Staff Depositor or Preservation Curator, I want to manage components of an existing FileSet components at a granular level in a user interface, so that I can adjust the contents and behavior of a FileSet over time

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic moves some of the more complex editing features for FileSets from release 0.3 to 0.4.

#### Links to Additional Information
Continues work from #119 (Edit/Manage AIP FileSets]

#### Checklist

- [ ] [UI Mockup for editing FileSets](https://docs.google.com/drawings/d/11wjr5PuMNjIArFCaXNoTbdPY1_r__XuEFv_Ezd3eWHQ/edit)
- [x] Delete a FileSet from an existing work
- [x] View all extracted Technical metadata on the View FileSet page
- [x] Interface to manage overall display order for FileSets within a work
- [x] Interface to edit the FileSet Use category assigned to an existing Set (Primary, Suppl. etc.)

- [x] Test what Hyrax "Versions" behaviors function in Hyrax when editing a File Set

To confirm if needed:
* Assign/change the default Thumbnail (consider Hyrax UI vs. custom Emory logic for thumbnails)
* Validate that at least one FileSet exists (may no longer be desirable depending on how parent/child works are configured for books)

De-scoped/moved to future epics:
- Change/replace a file for a given File Use within an existing Set
- Delete a File from an existing Set
- Provide navigation to edit/manage individual Files through the standard Hyrax File Manager, such as changing visibility or permissions for a specific file

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Some functionality was moved to a new epic for v.2 or later development phases. Additional note: Hyrax versioning does not function with our FileSet customizations.
