### ISSUE TITLE
Collections Form Revisions

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#494]
## Story
As a Collection Manager, I want to streamline the edit form for Collections, so that metadata entry process is more consistent between works and collections

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic splits out the acceptance criteria from the original epic #75 so that the form UI components can be addressed in a later release.

#### Links to Additional Information
[Collection Metadata Implementation Worksheet](https://docs.google.com/spreadsheets/d/17WLINPefxb0cQh2Jgx6H7XnUCDH8Ol1WlKaxtBAGW38/edit#gid=1472024349) - see the All Fields tab

#### Checklist
- [x] Fields in the form display with the value from the Display Label column
- [x] Non-administrators cannot create new sub collections within a collection ("Create sub collection" button)
- [x] Non-administrators cannot add existing collections as sub-collections ("Add Collection" button)

Deferred items:

- Fields should be grouped into sections like Works (Descriptive, Rights, Administrative)
- Selected Descriptive fields are hidden by default when the form loads (like Works)
- Rights and Administrative fields are always visible
- Fields display in the order specified on the worksheet
- Banner image upload guidance text indicates the appropriate display dimensions used in Lux (1110 x 440 pixels)

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
