### ISSUE TITLE
Configure Descriptive metadata properties for Works/Objects

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#61]
## Story
As a Metadata Specialist/Collection Manager, I want to configure Emory-approved Descriptive metadata for objects in the Cor repository, so that I can migrate existing metadata and provide rich description to support discovery for consumer users

#### Notes
This epic relates to object/work-level metadata in a generic work type. 

For RDF Predicate selection, the preferred URI is in the RDF Predicate column.
In some cases this may replace what Hyrax provides for a similar/equivalent property - if so, it's based on the recommendations of the Samvera MODS to RDF working group.

In some cases, predicates don't exist for properties we need. Placeholder URIs have been created using a base URL - this is a dummy link but we could configure this in reality in the future if needed because the Library owns the metadata.emory.edu domain.

In some other cases, a real predicate has been identified but additional granularity has been needed - in those cases an additional dummy #subproperty parameter has been added to the URI. 

Obligation/Requirement Level Notes
For the initial configuration, *Required* translates to required for the initial Curate work type. Enforcing other levels (Required if Applicable, etc.) will need to be addressed through the form interface or staff deposit/migration workflow later.

Display Labels for Lux/Curate
In general, use the Field Label unless something is specified in Display Label. In some cases we want to user-test the Display Labels for the Lux application, so Display Labels are generally incomplete.

Indexing Notes
These requirements indicate whether something should be indexed for search. Combined with the “Displays To” column, this is equivalent to whether something is searchable/visible in Curate (End users and Staff or Staff Only)  and/or Lux (End Users and Staff).

Facets
Preliminary facets for the Lux application were identified in the Discovery Phase but may need adjustment based on user testing. If this work needs to be started before we get user feedback, use the same facets for Curate as have been identified for Lux.

#### Links to Additional Information
[DLP Approved Metadata Worksheet - Objects: Descriptive Metadata tab](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=514733824) here

#### Checklist
- [ ] All fields in the Descriptive worksheet tab are configured for the appropriate model(s)
- [x] Required fields in the Obligation column are required for all works assigned to the initial Curate work type
- [ ] Preferred RDF Predicates are assigned from the RDF Predicate column
- [x] RDF Predicates using a emory.edu domain are not real - should not actually resolve but should be configured as placeholders
- [x] Repeatable or single-entry fields (more than one entry) are configured as noted in the Repeatable column
- [x] Facets are configured based on the Facet - Lux and Facet - Curate columns but may need adjustments based on user feedback
- [ ] Documentation about which model the property is configured for is provided for future reference

**Comment by rotated8** [comment]
Display labels will be part of work in a later release.

**Comment by eporter23** [comment]
Test notes: pending clarification on where Title is defined; adjustments for predicates for skos placeholders, series title, content genre
