### ISSUE TITLE
Configure Rights metadata properties for works

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#63]
## Story
As a Metadata Specialist, I want to implement Emory-approved metadata from DLP's Rights Metadata standard, so that I can utilize best practices in the metadata community for rights management and support rights compliance for our material

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic relates to object/work-level metadata in a generic work type. 

For RDF Predicate selection, the preferred URI is in the RDF Predicate column.
In some cases this may replace what Hyrax provides for a similar/equivalent property - if so, it's based on the recommendations of the Samvera MODS to RDF working group.

In some cases, predicates don't exist for properties we need. Placeholder URIs have been created using a base URL - this is a dummy link but we could configure this in reality in the future if needed because the Library owns the metadata.emory.edu domain.

In some other cases, a real predicate has been identified but additional granularity has been needed - in those cases an additional dummy #subproperty has been added to the URI. 

Obligation/Requirement Level Notes
For the initial configuration, *Required* translates to required for the initial Curate work type. Enforcing other levels (Required if Applicable, etc.) will need to be addressed through the form interface or staff deposit/migration workflow later.

Display Labels for Lux/Curate
In general, use the Field Label unless something is specified in Display Label. In some cases we want to user-test the Display Labels for the Lux application, so Display Labels are generally incomplete.

Indexing Notes
These requirements indicate whether something should be indexed for search. Combined with the “Displays To” column, this is equivalent to whether something is searchable/visible in Curate (End users and Staff or Staff Only)  and/or Lux (End Users and Staff).

Facets
Preliminary facets for the Lux application were identified in the Discovery Phase but may need adjustment based on user testing. If this work needs to be started before we get user feedback, use the same facets for Curate as have been identified for Lux.

#### Links to Additional Information
[Approved Metadata worksheet - Objects: Rights Metadata](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=1471556308) here

#### Checklist
- [x] All fields in the Rights worksheet tab are configured for the appropriate model(s)
- [x] Required fields in the Obligation column are required for all works assigned to the initial Curate work type
- [x] Preferred RDF Predicates are assigned from the RDF Predicate column
- [ ] Repeatable or single-entry fields (more than one entry) are configured as noted in the Repeatable column
- [x] Facets are configured based on the Facet - Lux and Facet - Curate columns but may need adjustments based on user feedback
- [x] Documentation about which model the property is configured for is provided for future reference

**Comment by eporter23** [comment]
Test notes: sensitive_material and sensitive_material_note should not be repeatable, otherwise good to go.
