### ISSUE TITLE
Configure controlled vocabularies for work/object metadata

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#65]
## Story
As a Metadata Specialist, I want to implement approved controlled vocabularies/terms, so that metadata that is either imported or created using a form utilizes standard term entries for better data management and end user searching

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic supplements the additional epics for configuring Descriptive, Rights, and Administrative metadata. Controlled terms/vocabs for each field are noted in the "Vocabs" Column of the worksheet.

See also #124 (auto-suggest fields).

#### Links to Additional Information
[Approved metadata worksheet - objects](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit?usp=sharing) 
[Controlled Vocabulary Usage Notes](https://docs.google.com/document/d/1kVkpjVMK5-tmQGuH0hJuXTafI5Ba3B3RarkGCiOeEtY/edit#heading=h.aztsqq5r400m)

#### Checklist
- [x] Controlled vocabularies identified in the object metadata worksheet can utilize locally managed terms or an external vocabulary
- [x] Controlled vocabularies identified in Descriptive metadata are configured for use
- [x] Controlled vocabularies identified in Rights metadata are configured for use
- [x] Controlled vocabularies identified in Administrative metadata are configured for use
- [x] For some fields, the terms entered may be either controlled or uncontrolled

**Comment by eporter23** [comment]
Changed to 0.3 after software engineering reviewed.
