### ISSUE TITLE
UI for post-ingest Preservation Workflows and Events

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#650]
## Story
As a Preservation Curator, I want to utilize a user interface for selected preservation activities, so that I can fulfill long-term preservation commitments in a self-service capacity without requesting developer time

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic is a catch-all for a number of user interface components needed to manage certain ongoing preservation workflow tasks. Currently many of these tasks must be performed by developers because there is no UI for them.

#### Links to Additional Information
[Wireframe for UI to run selected background jobs/rake tasks](https://docs.google.com/drawings/d/1I7pLwQFjB9Wlcc2-grcS0Ug04IymOqPXEySrxftoJqI/edit)

#### Checklist

Highest Priority
- [x] Curate administrators can initiate fileset cleanup task through a UI
- [x] Curate administrators can initiate selective reindexing by submitting a CSV in the UI
- [x] Curate administrators can load preservation workflow metadata by submitting a CSV in the UI

- [x] Tasks initiated in the UI can be monitored in sidekiq or some other mechanism, so that the user knows when the task is complete or if errors have occurred

Lower Priority
- [x] Create a new Manage Preservation Tasks area visible to Curate administrators only
- [ ] For tasks initiated in the UI that produce an output file, notify the requesting user that the file has been generated and where to retrieve it
- [ ] Curate users who have write permission to a work can add Deletion or Decommission workflow via a form
- [ ] User can monitor the status of an event or workflow
- [x] Selected events can be requested on demand outside a workflow
- [ ] Selected events can be enabled or skipped during a workflow
- [ ] User can provide notes and rights information on workflows and on selected events
- [ ] User can initiate a workflow (series of events) at the work-level
- [ ] User can append Ingest workflow metadata entries in order to correct mistakes
- [ ] Users can navigate to an option to create missing workflows metadata from the View Work page
- [x]  Users should not be able to edit Accession and Ingest workflow once it is created
- [x]  There should only be one instance of an Accession workflow stored for a work; and it is only generated if a user supplies workflow metadata.
- [x]  There should only be one instance of an Ingest workflow stored for a work; and it is only generated if a user supplies workflow metadata.
- [x]  Workflow metadata is encoded as metadata that can displayed in the Curate UI and/or exported as a file that can be exported as part of a preservation object for v.1+ versions of Curate

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
This will likely become a v.2 feature
