### ISSUE TITLE
Generic work type/digital object structure for Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#66]
## Story
As a Repository Administrator/Preservation Curator, I want to provision a generic work type for Curate users, so that our repository objects have greater consistency over time and align with our bit-level preservation strategy

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
In the DLP Discovery Phase and Technical Design Phase, we identified a goal of making our repository objects much more consistent than in the past. While individual objects/works will have distinct playback/presentation needs, utilize different metadata fields, or contain different file surrogates, these differences can be accommodated by a generic work model, a comprehensive metadata super-set, and format-agnostic IIIF viewer such as the Universal Viewer. 

#### Links to Additional Information
[DLP AIP specification](https://wiki.service.emory.edu/display/DLPP/Archival+Information+Package+Recommendations)
[DLP File Formats specification](https://wiki.service.emory.edu/display/DLPP/File+Format+Recommendations)  

#### Checklist
- [x] Work type will be expanded to support the DLP specifications above
- [x] Work type will be configured in future releases to contain a comprehensive, format/content-agnostic ingest and management form
- [x] Work type name: "curate-generic"

**Comment by tmiles2** [comment]
@eporter23 The related issues are completed can this epic be validated and closed?

**Comment by eporter23** [comment]
@tmiles2 @alexBLR @rotated8 I see the issues are closed but in some cases the checkboxes aren't checked off - if you can confirm these are done I can close the epic. Not something I can test.

**Comment by tmiles2** [comment]
@eporter23 Sounds good.

**Comment by eporter23** [comment]
Closing this - it will be expanded upon in 0.3 and 0.4.
