### ISSUE TITLE
Migrate Medical Artifacts Collection

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#734]
## Story
As a Collection Manager, I want to ingest the Medical Artifacts digital collection, so that I can provide long-term access to the material in a preservation repository

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Add notes here

#### Links to Additional Information
Medical Artifacts migration strategy document
General acceptance criteria for Phase 1 Migrations
Medical Artifacts metadata - Box | GitHub
Medical Artifacts QA test plan and samples
DAMS system - file naming and ordering conventions
Medical Artifacts SIP Mapping
QA test log

#### Checklist
- [x] Medical Artifacts Collection entity includes all supplied metadata
- [x] Medical Artifacts Collection entity and its works are assigned the designated Health Sciences Library and repository wide Participant groups at time of ingest in order to propagate Curate Edit/Sharing permissions
- [x] All populated Descriptive, Rights, and Administrative metadata fields supplied in the CSV are migrated and mapped to the Curate work model
- [x] Additional Preservation Workflows metadata is mapped to works generated by the import tool [can occur post-ingest if needed]
- [x] Number of works expected: 
- [x] Number of Files expected: 
- [x] Number of FileSets expected: 
- [x] Works and FileSets are generated according to the Medical Artifacts SIP mapping
- [x] FileSets are categorized using Emory categories (items are assigned to Primary Content)
- [x] FileSets are attached to provide multiple views of an artifact
- [x] FileSets are ordered using the part number from the filename convention
- [x] FileSets are labelled using a Part number from the filename ("Image 1", "Image 2") etc.
- [x] Standard access controls are assigned to the works 

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
