### ISSUE TITLE
Backup and restoration procedures

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#739]
## Story
As a Repository Administrator, I want to implement backup and restoration procedures for the preservation repository's data, so that the Libraries have a functional procedure for recovering from potential data loss

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic collects multiple tickets in progress by the DevOps team to ensure that we have backup and restoration capabilities for databases, AWS storage, Fedora, and SOLR. 

#### Links to Additional Information
Add [links](https://www.emory.edu/) here

#### Checklist
- [x] Backups for Fedora are created
- [x] Backups for application databases are created
- [x] Backups for S3 (including replication) are created
- [x] Backups for SOLR are created
- [x] Restoration processes are tested and documented

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Moving this work into 0.5 due to multiple AWS at Emory environment issues in October and November.
