### ISSUE TITLE
Preservation Health Reporting

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#742]
## Story
As a Repository Administrator or Preservation Curator, I want to receive preservation-focused updates on the overall repository, so that I can monitor trends in activity over time

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Among the highest priority of the Discovery Phase reporting requirements were requests related to top File Formats and Fixity Checking outcomes. Top File Formats (Top 5 or Top 20) are currently available to Administrator-level users in Hyrax.

#### Links to Additional Information
[Discovery Phase - Reporting Requirements](https://wiki.service.emory.edu/display/DLPP/Reporting+Requirements)
[Mockup - Top File Formats](https://emory.box.com/s/m5l8daiparbgd0nt7rt4r2fw8ynb2kwq)
[Mockup - Fixity Check Report](https://emory.box.com/s/mp430wb7ginir4trkjyneijlro5q957l)

#### Checklist
- [x] Reports can be broken into sub-reports if needed for implementation
- [x] Selected report data will be generated by customized queries, - OR - 
- [x] Selected report data may be gathered using Hyrax reporting capabilities and manually compiled
- [x] Requested reports data can be distributed to stakeholders on a quarterly basis using the Curate UI, Box, Wiki, or another means  

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
The priority preservation reports have been addressed through a semi-manual process. Reports are generated, compiled, and distributed in Box on a quarterly basis. Fixity check notifications are supplied from Hyrax notifications.
