### ISSUE TITLE
Deletion Activities in Curate UI

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#745]
## Story
As a Collection Manager, I want to use a Deletion workflow interface, logging, and tombstone capabilities to delete a digital object or collection and record the circumstances for doing so, so that we align with Emory's approved Digital Preservation requirements and Emory Retention Policy

As a Library Deposit Supervisor, Collection Manager, Repository Administrator, I want to be able to withdraw/delete a deposited file, so that I can remove copyright-infringing content deposited into the repository.

As a Repository Administrator, I want to restrict Hyrax ability to delete to Admins only, or via approval workflow, so that we can comply with Emory repository policy

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic describes functionality needed to restrict Delete capabilities for non-Administrator users. In Hyrax, the ability to Delete is unrestricted. By Emory Libraries Preservation Policy, we will not allow deletion of ingested objects except for certain circumstances.

#### Links to Additional Information
[Emory Libraries Preservation Policies: Retention Policy](https://wiki.service.emory.edu/download/attachments/119158582/Emory%20Digital%20Collections%20and%20Preservation%20Policy%20Suite.pdf?version=1&modificationDate=1564143815000&api=v2)

#### Checklist

Collections and Works - For non-Administrator users:
- [x] Instead of a Delete button, a Request Deletion option/button is displayed, OR - no Delete options are displayed, and a user must submit a ticket to LTDS
- [x] A user requesting deletion must submit Preservation Workflow Metadata explaining the reasons for why Deletion is needed

Collections and Works - For Administrator users:
- [ ] Notifications are sent, or a queue is established, for Administrators to review requests
- [x] Delete buttons (such as the standard Hyrax options) are available for Collections, Works, FileSets, Files
- [x] An option to record Preservation Workflow metadata for the Delete instance is available when a Deletion occurs

FileSets
TBD: whether FileSets may be deleted is closely tied to pending work in FileSet Editing epic #482

#### Given/When/Then
* Given 
I am a non-Administrator Curate user interacting with assets that I am granted permissions to modify
* When
I want to delete a Collection, Work, FileSet, or File
* Then 
I do not see standard Hyrax Delete buttons, or I am presented with a UI option to request deletion, which is then submitted, reviewed and completed by a Repository Administrator

**Comment by eporter23** [comment]
For v.1, notifications will be a manual process (email, support ticket etc.)
