### ISSUE TITLE
View Preservation Summary/Status from Work Pages

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#746]
## Story
As a Collection Manager or Preservation Curator, I want to to see a snapshot of preservation workflows and events on my objects, so that I know routine preservation checks have occurred, and I am alerted to any event failures for the object or its component files

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic revised the View Work page to include display of Preservation Workflow metadata and Event notifications for both Works and FileSets. For this release, we want to capture high level notifications, especially failures, that have occurred, but may not include all details for an event.

#### Links to Additional Information
[Mockup - View Preservation Workflow Metadata and Event Summary on View Work Page](https://docs.google.com/drawings/d/13zcaIugKDGV0G_y6lHsnXu9ztiu_HmtBptz71go_08w/edit)
*[Mockup - Link to Add Missing Preservation Workflow Metadata on View Work Page](https://docs.google.com/drawings/d/1wgSodRkHmyJq855-xlo11sjsY9DAUGrjqXSVEWGDQeQ/edit)

*The ability to add preservation workflow metadata via form is low priority and may be added in a future release.

See also related epic for viewing preservation event details

#### Checklist
View work page should:
- [x] include a new Preservation Status grouping of information
- [x] show Accession Workflow metadata if populated
- [x] show Ingest Workflow metadata if populated
- [x] alert a user to Event failures at the work level
- [x] indicate to users if there are no Event failures at the work level

Optional for 0.5:
- [ ] include a link to view additional detailed Event information for works or filesets (separate epic #747)
- [ ] link to a form that allows users to create Workflow metadata if not populated
- [ ] alert users to Event notifications at the File-Set level

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
