### ISSUE TITLE
View Preservation Event details for Works, FileSets

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#747]
## Story
As a Repository Administrator or Preservation Curator, I want to to see details of human or system-initiated preservation events and workflows that have occurred on the object, so that I know routine preservation checks have occurred, and so I can troubleshoot unwanted behavior in an object

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Users will want to see more detailed information about events summarized in the View Work, View FileSet Pages. This epic builds on the View Preservation Summary epic #746.

For v.1, we will list all events and workflows, because we don't anticipate that we will have that many occurrences per object. In future versions, we will look at options to truncate or filter the display as events and workflows become more robust.

#### Links to Additional Information
[Mockup - View Workflow and Event Details: Work-Level](https://docs.google.com/drawings/d/1_86XPEqC1XKKv6nNdsUPYYF0suKAkR3V1ZTrevOgJOw/edit)
[Mockup - View Event Details: FileSet-Level](https://docs.google.com/drawings/d/1A--1khkQlaDndQVu22cOKQjZTWRyC-tfFBbzaqlrM7k/edit)

#### Checklist
Work-level 
- [x] User can navigate from the View Work page to a more detailed view of Events (e.g. a new, separate page type)
- [x] User can navigate from the View Work page to a more detailed view of completed Workflows
- [x] A list of all completed workflows and accompanying metadata is displayed
- [x] A list of _all_ completed **work-level** events including all populated event data is displayed

FileSet-level
- [x] The Hyrax View FileSet page layout is adjusted to accommodate additional information sections (see wireframe)
- [x] _All_ completed preservation Events, passed or failed, for the FileSet are listed, including including all populated event data on the View FileSet page

#### Deferred
- [ ] A list of only _failed_ **FileSet** events is also provided, including a link to the FileSet(s) affected
