### ISSUE TITLE
Configure metadata properties for Collections

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#75]
## Story
As a Collection Manager, I want to populate Descriptive, Rights, and administrative/staff only information about the collection, so that I can record the context of its ingest and relate it to external systems  

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Collection metadata will be a smaller subset of what is provisioned for Objects, and the levels of requirement per field will be different in some cases. One or two new fields are needed that only are applied to collections. Controlled vocabulary use be the same as what was implemented for Works.  

#### Links to Additional Information
[Collection Metadata Implementation Worksheet](https://docs.google.com/spreadsheets/d/17WLINPefxb0cQh2Jgx6H7XnUCDH8Ol1WlKaxtBAGW38/edit#gid=1472024349) - see the All Fields tab

#### Checklist
- [x] Selected fields are required
- [x] Selected fields are repeatable
- [x] QA/vocabularies are the same as Works for the equivalent fields
- [x] Selected fields should validate entries as URLs
- [x] Selected fields should accommodate longer text entries (textarea)
- [x] RDF predicates can be re-used from equivalent fields in Work metadata

Items deferred to 0.5:
* Fields should be grouped into sections like Works (Descriptive, Rights, Administrative)
* Selected Descriptive fields are hidden by default when the form loads (like Works)
* Rights and Administrative fields are always visible
* Fields display in the order specified on the worksheet
* Fields in the form display with the value from the Display Label column
* Selected fields may be included in Facets (top priority is for the Collections' Titles to be browsable as a facet)

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
