### ISSUE TITLE
Accommodate strings and/or URIs from migrated metadata

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#76]
## Story
As a Metadata Specialist, I want to accommodate repository metadata values for controlled terms supplied either as a URI or a text string for the same metadata field, so that metadata from different originating workflows and sources can be searched and displayed to end users as human readable text, and external RDF-based authority data sources can be periodically refreshed

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
We anticipate that most of the objects ingested into Curate will use some kind of batch ingest method, and long-term, Curate will harvest metadata from Emory Libraries sources such as Alma and ArchivesSpace. 

DAMS and Marc records for Phase 1 migrations will contain some data stored both as text and a URI (e.g. rights statement.org values or Library of Congress subject headings). We can't always anticipate how this data will come through. In the DAMS, we store both the URI and the text value for rights statement.org entries, e.g.:

* In Copyright
* http://rightsstatements.org/vocab/InC/1.0/

Do we need to prefer one over the other? What does QA do related to data not entered through a form?

August 2019: [how Fedora stores strings vs URIs for controlled fields on our Curate work form](https://docs.google.com/document/d/1DWfLQXbKbbUbrfSnBYZ5LTLARUyypQ-WYF41OEoydPA/edit)

#### Checklist
Minimal/MVP: make the data loaded in batch compatible with the form. This may require more prep from our metadata in advance. 
- [x] Ingest/migrate data with the URI value if required by the form (e.g. right statements.org values)
- [x] Accommodate string values for other QA fields tied to external vocabularies if possible, because we will not always have a URI for those

Ideal/Long-Term	
- [ ] If a both URI and a string for the label are supplied for a metadata field, store both, but index only the string for Discovery/consumer display
- [ ] If only a URI is supplied, query the data source to get the text label and store it along with the URI	
- [ ] If only text exists, store the text only, and index and display the text for staff use and for the consumer front end

**Comment by eporter23** [comment]
As of 4/30, focus on strings and see how the release is going - to store URIs also and possibly parse out the URI for display.

**Comment by eporter23** [comment]
Moved this to revisit in 0.5

**Comment by eporter23** [comment]
From reviewing in Fedora objects, locally defined controlled term lists appear to store the URI only. Other QA fields (e.g. Subject - Topics) seem to store the string value only.

**Comment by eporter23** [comment]
Related to DCE importer work in progress, we have identified selected fields for which we will supply values as URIs to the importer. Other fields are either validated through the form's use of Questioning Authority or are accepted as strings. Dates must also be supplied as EDTF in order to validate in the form.

Thus far, testing has been successful on compatibility between CSV supplied metadata and the form.
