### ISSUE TITLE
Support for known, unknown, and approximate dates

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#77]
## Story
As a Metadata Specialist/Collection Manager, I want to provide date information about repository items with varying levels of precision, so that I can enable browsing, sorting, and filtering by date in a discovery interface

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
DLP Core metadata requires populating at least one type of date, but in some cases the exact date may be unknown, or contains a range of dates. Date Created is required if known for DLP metadata.

A primary need is that the value provided can be interpreted by Blacklight for sorting, and it should not contain unstructured text like "Circa" or "Approximately". Metadata imported from most of our legacy systems should provide machine-readable dates in W3CDTF or EDTF (at least in YYYY format).

#### Links to Additional Information
[Date validation for forms notes](https://docs.google.com/document/d/1A9hMl1ZNDbN2J4q77_6ixvq_wVW4gFJtxK-nnZKo5Tc/edit#heading=h.brpnvg8zad3u)
[DLP Approved Date Use Cases](https://wiki.service.emory.edu/pages/viewpage.action?pageId=119147632#Metadata/DataEntryFunctionalRequirements-DateEntries)
[Extended Date Time Format](https://www.loc.gov/standards/datetime/) 
[Duke's EDTF gem](https://www.google.com/url?q=https://duldev.atlassian.net/wiki/spaces/DDRDOC/pages/10813606/Dates%2BEDTF%2BImplementation&sa=D&ust=1549657340107000&usg=AFQjCNFQtr6xVf8jDl_4WNFahVYP6tD_sQ) 

#### Checklist
- [x] Date Created should require any entry in the form
- [x] For Date Created, if the date is unknown, either an Unknown option can be populated or the requirement can be bypassed OR the date can be entered in EDTF (XXXX-XX-XX)
- [x] For required date fields entered through an edit form, if some type of date is known, at least a four digit year (YYYY) must be supplied
- [x] For migrated data, either a machine readable unknown option can be populated or the requirement can be bypassed
- [x] For migrated data, if a date is known, it should be supplied at least to a four digit year (YYYY)

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by eporter23** [comment]
Ready to test once merged.
