### ISSUE TITLE
Restrict self-registration for Curate product login

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#79]
## Story
As a Repository Administrator, I want to prevent arbitrary individuals to self-register for a Curate user account, so that only approved Library Staff with expertise and collection affiliations have access to the repository

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Add notes here

#### Links to Additional Information
[Samvera slack discussion](https://samvera.slack.com/archives/C0F4P3FFF/p1548697444079800)
[GSU's workaround with Devise here](https://github.com/gsu-library/sirenia/pull/65) 

#### Checklist
- [ ] Library staff already identified as Admin users can login with their network credentials and see the Hyrax Admin UI 
- [ ] Library staff who do not have Curate group assignments cannot login with their network credentials
- [ ] Any user who does not have a Curate group assignment cannot login or see an option to create an account

#### Given/When/Then
* Given I am not a Library Staff member who is managing assets in the repository 
* When I encounter the Curate application and see a Login button
* Then I do not see an account creation/registration option as is visible by default in Hyrax

**Comment by eporter23** [comment]
Adding some additional test criteria. We can ask an LTDS team member who is not in the Curate Admin group to test with their credentials.
