### ISSUE TITLE
Bulk-ingest performance enhancements

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#920]
**As a preservation curator, I want to optimize our bulk import process, so that large ingests complete successfully and with less manual intervention to correct errors**

Notes

Checklist

Performance/stability:
- [x] Ingests complete successfully, generating the expected number of works and filesets
- [x] Number of background workers is scaled to optimize speed of ingest vs. stability/error rates
- [x] SOLR configuration is optimized to write data efficiently during bulk imports
- [x] File attachments complete as expected including thumbnail generation, characterization, and transfer to S3 storage
- [x] Non-developers can use a Curate interface to run Emory's file indexer/cleanup rake task
- [x] Large files ingested to Fedora/S3 can be downloaded from Curate without errors

Deferred items:
- [ ] Virus checking does not produce false positives or prevent uninfected files from ingesting
- [ ] Non-developers can use a Curate interface to run DCE's pre-processor rake tasks
- [ ] Ingests complete within reasonably similar durations, based on batch sizes

**Comment by eporter23** [comment]
Some incomplete tickets removed from epic.
