### ISSUE TITLE
CSV Importer Enhancements

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#928]
## Story
As a Preservation Curator, I want to expand the current CSV import process, so that additional metadata properties and SIP scenarios can be supported for bulk-ingest

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Add notes here

#### Links to Additional Information
Add [links](https://www.emory.edu/) here

#### Checklist
- [x] SIP mapping for LIMB output METS files should be set to Supplemental Preservation File
- [x] Additional/all Curate Generic Work fields can be supplied via CSV bulk import
- [x] The deduplication_key field in Curate can be added/edited in the Edit Work form (to correct a mistake, or to provide bulk-import support for manually-created objects in a Collection)

Lower Priority
- [ ] Assign appropriate representative media, thumbnail, and rendering options for IIIF
- [ ] Langmuir importer can be adapted to accommodate other DAMS collections
- [ ] Extraction and formatting of dates from Alma records
- [x] Pre-processor manifests can be generated for DAMS collections that do not follow the ARCH/PROD and front/back pattern can be generated
- [x] The importer can run refreshes on work metadata even if the files are not present in EFS
- [ ] Language codes can be translated to their labels (e.g. "eng" > "English")
- [x] Preprocessor incorporates only first four digit year from Alma records for date digitized

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
