### ISSUE TITLE
Curate Search and Display Enhancements

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#933]
## Story
As a Library Staff Depositor or Collection Manager, I want an enhanced user interface for search and display in the Curate product, so that I can search and preview data more precisely

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic is a catch-all for various user interface enhancements related to search, browse and display within the Curate UI

#### Checklist

Highest Priority items:
- [x] Configure facets for Curate: same as Lux facets OR a smaller subset
- [x] Enable searching by Cor ID and deduplication_key for works and filesets within the Dashboard search
- [x] Add the UV configuration from Lux to Curate's view work pages
- [x] Update Curate metadata field labels for Works and Collections (output the display label first, followed by the filename in parentheses; use the same display labels as Lux does)
- [x] Display the full collection Title in Edit Collection pages 
- [x] Hide/remove the single instance link section from View FileSet pages
- [x] Hide/remove the social media links on View Work pages
- [x] Hide/remove the Create Subcollection and Add Collection buttons on Collection pages

Lower priority items:
- [ ] Adjust timestamp display in Curate from UTC to local time
- [ ] Add selected dashboard information to the Curate homepage, or allow all users to see the Dashboard > Reports view
 - [ ] Ensure that Attach Child from View Work functionality works, OR remove this button from the View Work page
- [ ] Configure additional sort options in Curate: sort search results by Title in Public search

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
