### ISSUE TITLE
Upgrade to Hyrax 3 beta3

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#979]
Moving from beta1 to beta3 requires reviewing [~700 commits](https://github.com/samvera/hyrax/compare/v3.0.0.pre.beta1...v3.0.0.pre.beta3).

- [x] Review all the commits between beta1 and beta3
- [x] Identify any files with changes that we have overridden.
- [x] Update affected files to the new Hyrax version or remove the overwrite
- [x] Upgrade the Hyrax gem dependency to 3.0.0.pre.beta3
